== Capítulo I. Primeras Impresiones.

Muy pocos observadores de la naturaleza humana pueden pasar por alto cómo una disposición
enojada e iracunda es una de las primeras evidencias de la condición caída de los niños;
y es una que debería ser considerada mucho más seriamente y combatida más rigurosamente,
de lo que se acostumbra.
Confieso que cada vez que veo a personas que creen que es divertido
que un niño grite y tenga una rabieta para conseguir lo que quiere,
me estremezco ante el gran error que evidencian esas acciones.
¡Ay! ¡Cuán numerosos son los casos en los que, con el paso de los años,
esas risas de los padres se han transformado en lágrimas,
cuando los temperamentos desenfrenados de la infancia y la niñez (al haber
adquirido una fuerza incontrolable) recuerdan a los tan indulgentes padres
que la educación y la autoridad oportunos empezaron muy tarde!
Un buen consejo, con respecto a cada asunto que emprendamos,
y en especial en cuanto a la crianza de los niños,
es "`empezar por el principio;`" porque, para que la disciplina sea efectiva,
debe empezar con los primeros destellos de entendimiento,
y con las primeras manifestaciones de la voluntad del yo.
Porque un niño que es capaz de entender que quiere algo,
también es capaz de saber que no puede tener lo que quiere.
Y para que ustedes, queridos hijos, que leen este libro,
puedan ver la gran ventaja de ser debidamente sometidos
y advertidos por sus padres e instructores,
les relataré la historia de tres pequeñas niñas;
una de las cuales atravesó por algunas pruebas severas para ser alguien tan joven;
pero que, a través de la gracia de Dios (que es una promesa para los que piden por ella),
fue capaz de obtener una gran bendición a partir de todas ellas.
Esta niña, debido a sus dulces sentimientos, y a la gentileza de su comportamiento,
era usualmente llamada como "`Gentil Gertrudis.`"

Ella era la única hija del señor y la señora Belton,
y tuvo su primera experiencia dolorosa con la pérdida de sus dos amados padres,
quienes murieron con pocos meses de diferencia.
Su padre fue un misionero establecido en Calcutta, en las Indias Orientales,
y allí nació la pequeña Gertrudis,
y permaneció allí hasta que la muerte de sus padres
hizo que fuera necesario ser enviada a Inglaterra,
tanto para su protección como para su educación. Durante el viaje,
una amable señora se hizo a cargo de ella, que,
después de entregarla sana y salva en las manos de
un clérigo (que había sido un amigo de su padre),
se despidió de ella.

He aquí, la pequeña huérfana, con tan solo ocho años, y de naturaleza tímida y temerosa,
fue entregada completamente a extraños,
y algunos de esos extraños eran de una naturaleza muy desenfrenada.
Pero dejaré que se describan a sí mismos,
luego de haber dicho que el señor y la señora Allen,
la dama y el caballero con los que iba a vivir ahora,
tenían muy buenas intenciones con respecto a ella,
y que no era culpa de ellos si Gertrudis no era tan
apreciada por sus hijas como lo era para ellos.
Anhelaban que ella fuera feliz bajo su techo;
pero algunas veces ni los pobres señores Allen eran felices; y esto,
a menudo preocupaba y agobiaba a la pobre Gertrudis.

El problema era, que la señora Allen había sido muy indulgente con sus hijos,
y se había olvidado en muchas ocasiones de ese sabio principio de las Sagradas Escrituras:
"`Instruye al niño en el camino que debe andar;`"^
footnote:[Proverbios 22:6 Reina Valera de Gomez]
y también, de esa bendita declaración, de que,
"`Bueno le es al hombre llevar el yugo desde su juventud.`"^
footnote:[Lamentaciones 3:27]

Sin embargo, como acabo de mencionar, dejaré que estas cosas,
y que las personas se describan por sí mismas,
a través de las diferentes escenas y circunstancias
que ocurren en la historia de la pequeña Gertrudis;
solo mencionaré, que, además del señor y la señora Allen,
la familia estaba compuesta por dos pequeñas niñas, la mayor de once,
y la otra de nueve años, y un bebé de ocho meses.

La primera mañana siguiente a su llegada, la despertó el sonido de una campana,
y justo después, una mujer mayor de aspecto amable,
que ella había visto la noche anterior en la guardería,
y a quién ella había reconocido como la niñera,
llegó y le dijo que era hora de levantarse.
"`Vengo para vestirte, mi querida, si me lo permites,`" dijo Sara,
porque ese era el nombre de la niñera.
"`Gracias,`" dijo Gertrudis con un tono de voz un tanto somnoliento,
pues apenas se despertaba de un sueño profundo, que había sido así de profundo,
por haberse quedado despierta por tanto tiempo cuando se acostó por primera
vez en su cama pensando en su nuevo hogar y en sus nuevos amigos,
y preguntándose si iba a ser feliz con ellos o no.
Por fin, después de frotarse los ojos, de mirar a su alrededor,
y de estirar sus brazos un poco, comenzó a vestirse calmadamente, suspirando,
aunque no era su intención que Sara escuchara;
pues no quería hablar de lo que estaba sintiendo, porque si lo hacía,
ella creía que iba a llorar; y a Gertrudis le daba vergüenza de que la vieran llorar.
Algunas niñas son tan tímidas como ella; y no creo que sea un sentimiento malo,
siempre y cuando no sean obstinadas y orgullosas en su indisposición a ser vistas llorando.
Por lo tanto, examínense, queridos niños, cuando sus mentes están afligidas sobre algo,
y no saben cómo contenerse del llanto.
Digo que se examinen,
y si encuentran que están deseando ocultar su problema con algo como una risa escandalosa,
para que parezca que no les importa, entonces,
estén seguros de que la altivez y la terquedad de corazón los están gobernando;
y entregarse a eso es algo muy terrible.
Porque en la Biblia se nos dice, que "`todo corazón altivo es abominación para Dios;`"^
footnote:[Proverbios 16:5; Salmos 10:3]
y nada debería ser más temido, que convertirnos en objetos de abominación para Dios.

Sin embargo,
ni la obstinación ni el orgullo estaban presentes en los sentimientos de Gertrudis;
pero su extrema timidez natural y su indisposición para hablar con extraños,
la hicieron permanecer casi en silencio mientras Sara la ayudaba a vestirse.
Esto era tan diferente del comportamiento usual de quienes
estaban bajo su cuidado para vestirse y desvestirse,
que la niñera no pudo evitar notarlo.

"`Verdaderamente desearía que las señoritas Harriet y Charlotte
se quedaran tan quietas y calladas como tú,
mi querida,`" dijo ella, "`y así no tendría tanto trabajo en alistarlas como he tenido,
cada mañana de mi vida.
Pero de nada sirve que les hable;
pues mis palabras son menos importantes para ellas que el suelo que pisan.
Y también, hay tantos tirones y jalones, y esta tira está muy ajustada;
y la otra muy holgada--y falta un zapato o una media--y después,
¡tanto alboroto y cosas tiradas para buscarlos!
Oh, ¡qué gran trabajo!
Si no las hubiera criado desde bebés (y por eso no
puedo evitar amarlas tanto como si fueran mías),
estoy segura de que no lo soportaría.`"

Aquí, la niñera hizo una pausa,
quizás para darle una oportunidad a Gertrudis de hacer cualquier comentario breve.
Pero no tenía nada que decir; y después de un breve silencio, Sara cambió el tema,
y tras haber asumido el rol de narradora, ahora adoptó un rol más inquisitivo.

"`Entonces, mi querida, ¿has venido de un lugar muy lejos para vivir con nosotros?
¿Recuerdas a tu papá y a tu mamá, querida?
¿O eras muy joven para acordarte de ellos?`"

A la pobre Gertrudis le temblaron los labios, y su voz era casi imperceptible,
cuando respondió: "`los recuerdo muy bien.`"

La dulce Sara vio la tristeza envuelta en los recuerdos de la pequeña niña,
e inmediatamente intentó calmarla con palabras de ternura y ánimo.
"`Oh, vas a ser muy feliz aquí, mi querida, ¡no temas!`" dijo ella,
"`debes aprender un poco de la vitalidad de nuestras niñas,
y ellas deben aprender un poco de tu mansedumbre, y nos irá muy bien, no lo dudo.
Sólo que no debes permitirles imponerse sobre ti; porque son muy buenas en eso,
y si lo permites, nunca tendrás ni un momento de paz.
Ellas querrán tener los juguetes que tengas; ¡ay!,
incluso te los arrebatarán si lo permites.
Oh, esa señorita Harriet, ¡es una pequeña tirana cuando quiere algo y no lo puede obtener!
Así que asegúrate de cuidar bien tus juguetes, querida.
¿Tienes muchos?`"

"`Tengo una muñeca,
y una pequeña cuna;`" dijo Gertrudis con seriedad y medio temblando ante las
ideas de botín y saqueo que la descripción de la niñera suscitó en su mente.
"`No me gustaría perderlas.
No creo que me importen mucho mis balones, si deciden quitármelos.
Pero ¿crees que lo harán?`"

"`Oh no, mi querida; no si tienes el debido cuidado de no dejar que te dominen;
y puedes estar segura de que haré lo mejor para prevenirlo.
Pero ahora, habiendo terminado de vestirte, debo ir a levantarlas;
lo cual no creo que sea tan fácil.`"

Tan pronto como se fue la niñera, Gertrudis,
acostumbrada a la buena y necesaria práctica que le enseñó su querida madre,
se arrodilló al lado de su cama, y oró a su Padre Celestial;
y recordando lo que su amada madre le había dicho a menudo,
que no debía limitarse a las palabras que le habían
enseñado al ofrecer al trono de la Gracia,
hasta el punto de nunca permitirse usar otras,--sino que,
siempre que sintiera el deseo de pedirle cualquier cosa a su Padre que
está en los cielos que no acostumbraba mencionar en sus peticiones diarias,
debía someterse a ese deseo,
y expresarlo según como lo sentía. Así que dio rienda
suelta a lo que brotaba de su corazón,
y con fervor rogó al Señor que la cuidara y la hiciera feliz en su nueva circunstancia,
pues era muy infeliz ahora.

Sus lágrimas culminaron lo que sus palabras no pudieron; y se encontraba arrodillada,
con su cabeza sobre sus manos,
cuando la puerta se abrió y la señora Allen entró al dormitorio.

Gertrudis se levantó inmediatamente, y confundida,
estaba a punto de limpiarse las lágrimas; pero la señora Allen,
al percibirlas en sus mejillas, la acercó tiernamente hacia ella,
y después de haberla besado y expresado la satisfacción que sentía
al haberla encontrado tan comprometida en sus deberes matutinos,
dijo: "`Mi amor,
¿qué es lo que aflige a tu pequeño corazón? ¿No crees
que vas a ser feliz en tu nuevo hogar?
Oh, espero que lo seas.`"
La bondadosa voz fue bastante abrumadora en ese momento,
haciendo estallar en lágrimas a Gertrudis.

La señora Allen esperó hasta que ella se calmara un poco,
y luego le repitió que esperaba que la pequeña niña pudiera ser feliz con ellos.
Aún así, Gertrudis mantuvo silencio; y la dama,
casi temiendo que este comportamiento fuera el resultado
de una disposición más bien de tipo melancólica,
se dirigió a ella en un tono más serio.

"`Me temo, querida,`" dijo,
"`que estás propensa a darle rienda suelta a tu tristeza . ¿No te hemos mostrado,
con toda la bondad que está a nuestro alcance en el corto tiempo que hemos estado juntos,
que deseamos hacer todo lo necesario para que estés a gusto?`"

Ella se quedó esperando una respuesta, y Gertrudis respondió muy suavemente: "`Sí,
señora.`"

"`¿Y qué es, entonces, lo que te hace pensar que no serás feliz?, mi amor.
Porque me parece muy claro que estás pensando eso.`"

"`Tengo miedo de no gustarles a Harriet y a Charlotte, señora.`"

"`Oh, ¿eso es todo?
Entonces, no temas,`" dijo la señora Allen.
"`Son unas niñas bastante fogosas, sin duda alguna; pero tienen corazones muy buenos;
y estoy segura de que te amarán, y yo también, e igualmente el señor Allen.
Así que, seca tus lágrimas, y ahora ven conmigo a desayunar al comedor,
donde nos reunimos a esta hora de la mañana para la adoración en familia.`"

Luego tomó a Gertrudis de la mano,
y la llevo hacia abajo a la habitación donde el señor Allen
estaba sentado a la mesa con la Biblia ante él,
esperando que llegara el resto de la familia.
Saludó a la pequeña Gertrudis muy cariñosamente,
y le pidió que tomara asiento donde él le señaló,
y luego sonó la campana para llamar a los otros miembros de la familia.

Se oyó entonces un bullicioso zapateo,
y en seguida Harriet y Charlotte llegaron en un gran alboroto al salón,
en compañía de las criadas de la familia.

El señor Allen se dirigió a las niñas con unas cuantas
palabras de desaprobación por haber llegado tan tarde,
que no parecieron ni escuchar ni importarles;
porque toda su atención estaba fija sobre la joven visitante Gertrudis,
cuyo nuevo vestido mañanero les llamó su atención,
y cautivó su atención por un largo rato después de que su papá hubiera comenzado a leer.
Al rato, la señora Allen les indicó con una mirada y con un movimiento de cabeza,
que ella había observado su indebido comportamiento,
ante lo cual ellas se calmaron y aparentaron prestar más atención a lo que acontecía.

La porción de la Escritura que se leyó fue el último capítulo del evangelio de Juan;
y lo que se dijo de ello fue muy fácil de entender,
y Gertrudis se sintió consolada con ello.
El dulce espíritu de amor que se respira a través del lenguaje y la conducta del amado
Redentor hacia el hacia pobre Pedro arrepentido fue resaltado por el señor Allen;
parecía muy deseoso de enfatizar la lección que esta historia era capaz
de impartir a las mentes de los que estaban alrededor de él.

"`¡Cuánta ternura,`" dijo,
"`tiene nuestro piadoso Salvador con todo Su rebaño! ¡Qué buen Pastor,
que no sólo cuida Él mismo de las ovejas y de los corderos,
sino que los pone a cargo de otros,
ordenándoles que sean bondadosos con ellos también!`" "`Porque no piensen
que este mandato que les estoy leyendo fue dado solamente a Pedro.
Fue dado a todas las personas que tienen el poder y la oportunidad
de instruir e influenciar las mentes de sus prójimos.
Especialmente se les da a los padres, y a las cabezas del hogar.
Se me ha dado a mí, en este momento.
Sí, en este momento, me parece escuchar la voz de mi Maestro decirme,
'`¡apacienta Mis ovejas,
apacienta Mis corderos!`' ¿Y cómo los apacentaré? ¿Acaso
la comida externa que está ahora delante de nosotros,
es la que el Señor me ordena que les dé de comer?
No, amigos e hijos,
estoy seguro de que no hay nadie aquí tan ignorante como para suponer
que ese es el alimento del que me veo obligado a proveerles.
Es el pan vivo que desciende de Dios el que se me ha encomendado poner delante de ustedes.
El pan del que se habla en este libro bendito; es decir, Aquel que dice de Sí mismo:
'`Yo soy el pan vivo.`'`"

"`¡Es Él a quien debo presentarles en toda Su hermosa naturaleza!
A Cristo Jesús, el Salvador de los pecadores, muriendo para que puedan vivir.
El Hijo de Dios, hecho Hombre, para enseñarles lo que (como seres humanos) han de sufrir,
hacer y ser.
El Cordero de Dios, llamando a los duros y a los violentos, a aquellos que,
habiéndose perjudicado a sí mismos primero al no controlar
sus temperamentos y negar su obstinada voluntad,
no tardan en causar daño a sus prójimos; llamando a estos para que se acerquen a Él,
porque Él es manso y humilde de corazón, y con Él encontrarán descanso para sus almas.
Él es al que debo predicarles.
Él es al que deben acercarse.`"

"`Pero ahora, queridos hijos,
tal vez no sepan qué significa este '`acercarse a Jesús.`' Bueno,
trataré de explicárselo lo mejor que pueda.
Supongan, (y el buen hombre suspiró, mientras hacía una pequeña pausa,
y hablaba con mucha solemnidad,) supongan, que algunos de nosotros, --ustedes niñas,
por ejemplo, se encuentran angustiadas, con temperamentos muy impetuosos e impulsivos;
quieren algo y no lo pueden obtener; o creen que han sido injustamente tratadas,
y están muy enojadas, deseando vengarse; o quizás algo o lo otro,
las pone en un estado furioso, y en este estado hacen o dicen algo imprudente.
Tal vez se insulten unas a otras; o hagan comentarios maliciosos, o tal vez, (porque ¡ah,
he visto tales cosas!) lo lleven más allá como para
pelearse y pincharse las unas a las otras;
y luego, cuando el episodio de ira haya pasado, y se hayan tranquilizado,
se avergüenzan (y tienen buenas razones para estarlo) de tan vergonzosa conducta,
y desean no haber cedido ante ello, y se prometen nunca más hacer algo parecido.`"

"`Pero,
esto es lo mismo que prometerse a sí mismas que nunca más volverán a comer ni a beber;
porque si ser rudo, impulsivo, e iracundo es parte de su naturaleza,
para ustedes es tan natural decir cosas desagradables,
y pelear y pincharse cada vez que se enfrenten con algo que les desagrade,
como les será tan natural comer y beber la próxima ocasión que tengan hambre.
Su único refugio y camino de ayuda está en obedecer
al llamado del Cordero bendito de Dios,
y acudir a Él en busca de ayuda.
Y es de esta manera que debes ir a Él. Siempre que sientan el pecado
y la humillación por haberse rendido ante una mala inclinación,
y se encuentren avergonzadas de ello,
quédense quietas por un rato y esfuércense por valorar
y amar esos sentimientos buenos de arrepentimiento.
Nunca, nunca, traten de descartarlos porque les parezcan dolorosas o desagradables;
sino que aférrense a ello tanto como puedan, porque provienen de Dios,
y son Sus reprensiones de instrucción que conducen al camino de la vida.
Ahora,
miren esa porción de las Escrituras en donde Jesús invita
a los pecadores a que vengan y aprendan de Él. Aquí está,
se las voy a leer.`"

El señor Allen fue entonces al capítulo 11 de Mateo,
y leyó a partir del versículo 25 hasta el final.

"`Cuando hayan hecho esto,`" continuó, "`traten de pensar en esa expresión,
'`aprended de Mí,
que soy manso y humilde de corazón.`' Traten de pensar
qué espíritu más dulce se describe aquí,
y ¡qué tan hermoso es un corazón manso y humilde!
Todas las cosas realmente hermosas son gentiles, y humildes, y felices, y contentas.
Se encuentran en paz consigo mismos, e inspiran paz a otros.
Cuando vimos a su hermanito ayer, acostado en su cuna,
observando su pequeña mano y sonriendo, y a su modo, hablando y jugando con ella,
les propongo que consideren, ¿qué fue lo que hizo que mamá lo tomara,
y lo apretara contra su corazón, como si lo amara más que nunca?
Y tras haberlo considerado, verán que fue la verdadera belleza del estado inocente,
humilde y contento del corazón,
que el bebé mostró. Hasta el temperamento más feroz se habría calmado,
al menos por un momento, al contemplar al bebé, tan sencillo y serenamente feliz.
Cuánto más, entonces,
se pueden controlar nuestra ira y nuestra fuerte voluntad al contemplar el carácter
manso y humilde de Aquél que fue llamado el santo Hijo Jesús.`"

"`Por lo tanto, acercarse a Jesús es pensar en Él,
leer las descripciones de Su carácter hasta que puedan ver su belleza;
y luego rogarle para que produzca tal amor en sus corazones
por Su dulce y humilde temperamento y Su espíritu inocente,
que tengan hambre y sed de experimentarlos.
Y pueden estar seguras de que no tendrán que esperar mucho tiempo
antes de que sientan un deseo que crece por todo lo que es tierno,
manso y humilde.
Habrá una naturaleza nueva, como una pequeña y encantadora flor,
creciendo en sus corazones.
Y cuando sientan su dulzura, y la cuidadosa atención que requiere,
orarán fervientemente a Dios que la preserve para ustedes,
y que la salve de la bestia salvaje de sus propios sentimientos corruptos y pecaminosos.
Orarán como David, '`Rescata mi alma de sus destrucciones, mi vida de los leones.`'^
footnote:[Salmo 35:17]
Oh, una vez que hayan probado que el Señor es misericordioso, y hermoso, y lleno de amor,
y manso y humilde de corazón, estarán tan temerosas de enojarse, o vengarse,
o dejarse llevar por una emoción fuerte,
como mamá hubiera tenido miedo ayer de poner a su
inocente y sonriente bebé en una guarida de dragones.`"

El señor Allen cerró la biblia, y después de una corta pausa, se arrodilló para orar.
Más de un corazón se unió a sus fervientes súplicas para que un gran derramamiento del
Espíritu de amor y mansedumbre descendiera y vistiera sus almas con paz y humildad;
pero ninguno experimentó una unidad más profunda
en este santo ejercicio que su nueva huésped,
la pequeña Gertrudis.

Casi involuntariamente, en cuanto los criados se retiraron,
ella se acercó suavemente a su silla.
Había algo en él que le recordaba a su querido padre;
y esperaba en su corazón que él la amara,
como estaba segura de que ella lo amaría a él. Ella estaba de pie cerca de él,
temerosa de entrometerse, pero deseando llamar su atención, cuando la mayor de las niñas,
y de pronto la otra también,
la llamaron para ir a correr en el jardín mientras se hacía el té.

Como el tono de sus voces era alto y acelerado,
logró sacar al señor Allen de su silencioso estado de meditación, y al volver su cabeza,
percibió los dulces ojos marrones de Gertrudis que estaban fijos sobre él,
y una pequeña sonrisa en su boca, que parecía decir, "`buen señor,
quiero que me digas unas palabras amables.`"

Al menos,
esto parecía ser la interpretación que el dedujo basada en la expresión de su rostro;
por lo que, tomándole de la mano y acercándola más hacia él, la besó con amor paternal.
"`Bueno, mi pequeña Gertrudis,`" dijo,
"`¿crees que te gustará vivir aquí? Espero que seas muy feliz,
y ten por seguro de que estaremos encantados de tenerte con nosotros.`"

"`Estoy segura de que...`" --luego hizo una pausa,
como si temiera hacer una confesión demasiado arriesgada.

"`¿Estás segura de qué, mi amor?`"
dijo el señor Allen.
"`Estoy segura de que te amaré, señor--me haces recordar a mi querido papá.`"

El señor Allen sonrió, y estaba a punto de decir algo; pero las dos pequeñas niñas,
que durante esta escena habían estado de pie junto a la puerta,
al estar bastante cansadas de esperarla,
fueron a donde ella y tomándola de las manos una por un lado y la otra por el otro,
corrieron con ella hacia el jardín.

"`Ven, quiero que me digas qué juegos te gustan más,`" dijo Harriet, la mayor de las dos.
"`No te voy a dejar que te quedes callada de esa manera tan miserable.
Te mostraremos un poco de diversión, y te animaremos un poco.
¿Puedes subir a un árbol, o saltar una cerca?`"

"`Oh no, no puedo,`" dijo Gertrudis,
encogiéndose y estremeciéndose ante la situación que se le presentaba.
"`Nunca he subido a un árbol en mi vida; y no sé saltar sobre nada.`"

"`Bueno, entonces te enseñaré. Sólo mírame subir a ese viejo árbol morera.
¿Ves lo baja que es esa parte donde se ramifica?
Charlotte y yo nos sentamos a menudo allí. Subiré ahí en un minuto.`"

"`Oh, por favor, no lo hagas,`" dijo Gertrudis,
"`puedes caerte y lastimarte--te rasgarás el vestido,
te--`" Pero sus palabras no fueron escuchadas.
Pronto subieron por unos escalones al pie del árbol, y Harriet habiendo subido,
estaba invitando en voz alta a las otras dos para que la siguieran,
cuando escucharon un llamado invitándolas a desayunar.
Lamentando mucho la brevedad de su diversión, Harriet bajó del árbol de mala gana,
y junto con su hermana y Gertrudis entró a la casa con una parte de su vestido arrastrándose
por el suelo debido a un gran desgarre que se había hecho tras subirse al árbol.
En cuanto a Gertrudis,
se sintió casi como una delincuente por haber sido una espectadora de tales hechos,
temiendo que ocasionaría una fuerte reprimenda por parte
de la señora Allen tan pronto como viera el vestido dañado.
Pero, después de quejarse de que siempre debía esperar a sus hijas,
y que siempre rasgaban sus vestidos y hacían travesuras,
la buena señora no habló más sobre el tema.

