== Capítulo II. La Institutriz.

Durante las primeras tres semanas desde de la llegada de Gertrudis,
no hubo mucha disciplina o instrucción para las jóvenes de la casa,
ya que durante la mayor parte de ese tiempo el señor Allen
se encontraba ausente en Londres por motivos de trabajo;
y cuando no estaba presente,
la única restricción que parecían percibir las dos niñas era eliminada completamente.
Ellas hacían lo que querían con su mamá;
y a pesar de que se le escuchaba decir con frecuencia a lo largo del transcurso del día:
"`Mira, mi querida Harriet, no hagas eso,`" o, "`Charlotte,
no permitiré esto,`" no puede decirse que le hicieran caso.
De hecho, su indulgencia produjo tanta desobediencia,
que parecía que expresaba sus deseos y expectativas
sólo porque sabía que era lo correcto expresarlos,
pero no como si esperara que la escucharan y obedecieran.
El ruido y la confusión, los golpes en las puertas, el arrojar los banquillos al piso,
el desorden en las sillas y en las mesas con ropa de muñecas, juguetes,
y todo tipo de basura, las discusiones y las peleas, y luego las risas desenfrenadas,
parecían ser la actividad principal de Harriet y Charlotte Allen.
A este tipo de conducta, se añadían ocasionalmente las bromas a Gertrudis,
escondiendo su muñeca, o algunas veces colgándola de una cuerda en el árbol de morera;
llenando su pequeña cuna con piedras, pequeñas ramas, hojas secas,
y otras cosas por el estilo, arrojando sus balones por encima de los arbustos,
y muchas bromas más de mal gusto,
que eran muy difíciles de soportar para una niña de espíritu apacible como Gertrudis.

Su único refugio en esos momentos era quedarse al lado de Sara en la guardería,
donde siempre se sentía segura de estar protegida,
y donde se le permitía realizar sus discretas y tranquilas
formas de entretenerse sin interrupción. Aquí,
también, encontró una fuente inagotable de diversión,
en la estrecha amistad que cultivaba con el pequeño Johnny Allen;
--un niño saludable y feliz,
que recién comenzaba a demandar mucho entretenimiento y atención.
Gertrudis se sentía feliz de poder ofrecerle ambas cosas,
mientras se sentaba a su lado en la alfombra;
y Sara (que ya no era tan joven) se sentía feliz de compartir la difícil
tarea de tener que agacharse y obedecer los deseos de un niño enérgico,
que quiere todo lo que ve, con el único fin de tirarlo al piso,
y darles a otros la molestia de recogerlo una y otra vez.
Satisfecha con la presencia de la pequeña ayudante,
y con el hecho de poder supervisarlos al mismo tiempo,
la niñera se sentó en su mesa de trabajo mientras Gertrudis y Johnny,
divirtiéndose y sintiéndose entretenidos,
disfrutaban de la vida de una manera más inocente que la mayor parte de
las personas de la casa durante la ausencia del señor Allen.

Por fin se acercó el momento de su regreso;
un momento muy anticipado que se mezclaba con una variedad
de sentimientos entre los diferentes miembros de la familia;
pues debo informarles, que él no iba a regresar a casa solo,
sino que iba a traer consigo a una mujer llamada señorita Robson, que,
en conformidad con sus desos, había accedido en asumir el cargo de institutriz.
Les brindaré una pequeña descripción de esta dama,
para que se formen alguna idea de alguien de la que escucharán
hablar mucho a lo largo de nuestra historia.

La señorita Robson era una persona de buen entendimiento y de una formación respetable,
que había estado acostumbrada a la educación de los jóvenes desde los dieciocho años;
y como ahora tenía treinta y ocho, supondrán que, durante tan largo período,
unos veinte años (en los que había aprendido a tratar
con los temperamentos y hábitos de los jóvenes),
se había formado una idea bastante clara en cuanto al método más adecuado de tratarlos.

De hecho, fue debido a la buena opinión que él tenía de su discernimiento y criterio,
(porque ella era una pariente lejana de él,
y la conocía desde hacía muchos años) que el señor Allen la había
contratado como institutriz de sus pequeñas niñas.

Muchas otras personas, en diferentes ocasiones, ya habían ocupado ese rol en su casa,
pero ninguna de ellas había permanecido por más de unos cuantos meses.
Los severos e ingobernables temperamentos de las niñas,
y la indulgencia imprudente de su madre,
habían dificultado la tarea de intentar educarlas correctamente, de modo que,
después de un pequeño esfuerzo,
la institutriz solía abandonarlas por algo que le prometía
una mejor recompensa por sus esfuerzos.

Pareciera extraño que un hombre tan bueno como el señor
Allen no fuera capaz de manejar mejor a su familia;
pero el hecho era que, al atender los deberes de su iglesia,
y otros asuntos relacionados con su trabajo,
su tiempo estaba tan ocupado que se vio obligado a delegar
gran parte del manejo de sus hijos a su madre;
que, aparte de ser la responsable de consentirlas demasiado, a menudo estaba muy enferma,
y era incapaz (debido a su débil estado de salud
y de ánimo) de controlarlas como era debido.
Además de estas circunstancias,
había otra que afectaba a estos padres de corazón muy tierno y que,
como ustedes pueden suponer, amaban mucho a sus hijos.
Se trataba de que habían perdido varios hijos en los años de infancia;
lo que los hacía aferrarse con cierto "`afecto desmesurado`"
a los que la Providencia había querido preservar.
Oh, queridos niños, ¡ustedes conocen muy poco,
y por tanto consideran muy poco (en general) lo que sus padres atraviesan por ustedes!
La atención que les deben, por muy fiel que sea,
apenas puede compararse con las angustiantes preocupaciones,
y las diversas esperanzas y temores, que han tenido que sufrir por causa de ustedes.
Esto es especialmente cierto durante el tedioso y algunas
veces enfermizo período de su infancia y temprana niñez,
cuando ustedes no tienen ninguna habilidad para entender ni preocuparse por sus sufrimientos;
pero que para ellos fue una temporada de amor y tierna vigilancia,
que los impulsó a esforzarse constantemente para aliviar
y soportar la carga de sus más pequeñas molestias.
Oh, si hay algo que debe escandalizar y provocar reacciones desagradables,
al punto de ser repulsivas,
es presenciar a los padres siendo tratados con irrespeto o falta
de amabilidad por los mismos hijos que han llevado en sus brazos,
que han acercado junto a sus corazones, que han alimentado y cuidado,
y que en la medida en que los medios humanos lo han permitido,
les han proporcionado todas las comodidades y ventajas que un niño pueda poseer.

Pero no debo hacerles suponer que el caso de Harriet
y Charlotte Allen fuera tan triste como éste.
No puedo predecir lo que podría haber sido de ellas si les hubieran permitido
continuar por unos cuantos años más en esta condición de indulgencia,
con sus emociones fuertes y temperamentos alocados,
tan descontrolados como lo eran en este momento.
Pero dichosamente para ellas, la firme y sana instrucción de la señorita Robson,
estaba a punto de poner un alto a su peligrosa conducta.

Esta dama, como les comenté,
estaba acostumbrada al manejo de los niños desde su juventud,
habiendo sido educada con la intención de obtener su sustento de esta manera.
Ella era, en el sentido más sincero de la palabra, una cristiana;
una que temía a Dios y que amaba justicia; y como tal,
que no se deleitaba en las vanidades y costumbres del mundo.
Quizás, a algunos les parezca que ella no tenía gran mérito en negar tales cosas, ya que,
por su posición como institutriz,
era muy probable que no se enfrentara con muchas tentaciones.
Sin embargo, deben recordar, que no es siempre el hacer o no hacer algo en particular,
lo que determina nuestro carácter y muestra lo que realmente está en nuestros corazones.
Porque, por un lado,
hay algunos que participan involuntariamente en las actividades mundanas,
simplemente porque se encuentran en circunstancias
en las que no pueden seguir sus buenas inclinaciones.
Y por otro lado,
hay muchos más cuyo corazón y voluntad desean participar y seguir los deseos mundanos,
pero que se encuentran en situaciones en las que se ven obligados a negarlos.
Ahora, queridos niños, ¿pueden ver, que esas personas que, si pudieran, serían alocadas,
mundanas, a favor de la moda, "`amadores de los deleites más que de Dios,`"^
footnote:[2 Timoteo 3:4]
realmente son todo eso ante los ojos de ese Gran y Santo Ser que no ve como el hombre ve;
porque el hombre ve la apariencia externa,
pero el Señor mira el corazón. No cabe duda de que lo son;
porque tal como son nuestra voluntad y nuestros deseos, así somos nosotros;
independientemente de que seamos capaces o no de gratificar esa voluntad y esos deseos.
Y fue porque el señor Allen era consciente de esta verdad,
que deseaba tan fervientemente que la señorita Robson instruyera a sus hijos.
Él sabía muy bien,
que de nada le iba a servir a la institutriz hablar en contra
de la inutilidad y la vanidad del amor por el vestido,
o de lo pecaminoso del mundo y sus afanes,
si ella misma seguía tales modas en la medida de lo posible,
esforzándose más por inculcar en las mentes de sus pupilos
el temor de ser incultos que de ser impíos. Por lo tanto,
su gran preocupación,
era poner a sus pequeñas hijas bajo el cuidado de
una persona que modelara las verdades de la Biblia;
y no alguien que solamente hablara de ellas.

Él creía plenamente que la señorita Robson era así. La conocía desde que era joven,
y la había visto (en circunstancias y apuros muy
difíciles) mantenerse firme en esa fe en Dios que,
en palabras de un antiguo escritor, "`anclaba su alma inmortal a su Obispo.`"^
footnote:[El Diario de George Fox]
Se alegró, pues, de retrasar su regreso a casa tras esta visita a Londres,
y así tener el placer de llevarla consigo como un miembro más de su familia.

El señor Allen estaba muy contento;
pero su esposa no compartía exactamente el mismo sentimiento.
La señora Allen también conocía a la señorita Robson, y aunque respetaba su carácter,
deseaba en su interior que se hubiera elegido, como institutriz para sus hijos,
a una persona con un modo de pensar y de actuar menos estricto.
Pero, como siempre tenía la costumbre de someterse a los deseos y el criterio del señor Allen,
y sabía que desde hacía mucho tiempo él solo esperaba que la señorita Robson terminara
de concluir un compromiso de trabajo antes de proponerle un lugar en su familia,
reprimió sus pensamientos con respecto a este tema,
y se preparó para recibirla con la mayor amabilidad y buena voluntad posibles.

Para las pequeñas niñas, la señorita Robson era una completa extraña;
y varias (como ustedes pueden suponer),
fueron las conjeturas que pasaron por sus mentes sobre quién y cómo sería ella;
y si les gustaría o no tanto como algunas de sus institutrices anteriores.

Estaban de pie frente a la ventana de la guardería, junto con Gertrudis,
cuando el carruaje, que había sido enviado al pueblo vecino para recogerlos,
llegó cerca de la puerta con su papá abordo, y con una dama que, por supuesto,
era la esperada señorita Robson.
Las exclamaciones de alegría al ver a su padre, y de curiosidad por la desconocida,
retrasó su habitual tarea de ponerse el vestido de la tarde.
Todas las cabezas buscaban abrir paso para ver a la recién llegada.
Incluso el pequeño Johnny que se encontraba en los
brazos de Sara y que estaba detrás de ellas,
parecía entender que algo nuevo y extraño estaba ocurriendo en el mundo.

"`Bueno, ¡nunca he visto una mujer así!`" fue la primera exclamación de Charlotte.
"`Pero ¡está vestida tan simple como Sara!`"

"`¡Qué sombrero de paja tan viejo!`" dijo Harriet, "`y, ¡madre mía,
mira qué vieja se ve!`"

"`No creo que vaya a poder obedecerla tanto,`" continuó Charlotte.

"`Puede que ella sepa cómo hacerte obedecer;`" dijo Sara,
"`y aunque lleva puesto ese viejo sombrero, no sabes lo que hay debajo de él.`"

"`Estoy segura de que tiene una cara muy fea,`" respondió
Charlotte muy disgustada por el comentario de Sara.

"`La verdadera belleza se reconoce por sus frutos,`" dijo Sara,
"`y me atrevo a decir que en poco tiempo veremos, que ella posee la verdadera belleza.`"

Gertrudis permanecía en silencio durante este diálogo,
que terminó con la palabra de la señora Allen,
llamando a los niños para que bajaran a ver a su padre,
y se sorprendió de que no hubieran terminado de cambiarse sus vestidos.

Esto lo hicieron rápidamente,
y Harriet y Charlotte se apresuraron a bajar las
gradas para darle a papá un cálido beso de bienvenida.
Gertrudis estaba contenta de quedarse atrás por un corto tiempo; porque,
aunque nadie en la casa podía estar más feliz del regreso del señor Allen,
no tenía prisa por conocer a la señorita Robson,
a quien esperaba encontrar muy intimidante.
Esta expectativa había surgido en la pequeña Gertrudis no por alguna
descripción clara o precisa que hubiera recibido de esta dama,
sino solo por las imprecisas insinuaciones que la señora Allen
ocasionalmente dejaba caer a lo largo de las dos últimas semanas,
siempre que Harriet y Charlotte se mostraban más rebeldes de lo normal;
y estas insinuaciones siempre apuntaban a la probabilidad
de que su conducta iba a ser corregida muy pronto.

"`¡Muy pronto verás lo que dirá la señorita Robson al respecto!`"
era lo que usualmente decía cuando sus objeciones en contra
de esto o de lo otro era desatendidas por sus hijas.
Así es como Gertrudis aprendió a relacionar algunos sentimientos bastantes
alarmantes con el mero nombre de la nueva institutriz.

Por lo tanto,
para ella fue de gran alivio bajar con Sara y con Johnny para ver al señor Allen,
y encontrar que la señorita Robson había dejado la
habitación para ir a prepararse el almuerzo;
y como las niñas ya habían almorzado,
Gertrudis solamente esperó recibir la amable bienvenida del señor Allen,
y luego se retiró con ellos a la guardería.

Por la tarde, en la mesa de té, se encontraron por primera vez con la señorita Robson,
a quien la encontraron sentada tan solo con la señora Allen,
pues el señor Allen estaba ocupado en su oficina con uno
de sus feligreses que había llegado por asuntos de trabajo;
y, como era probable que se atrasara por un tiempo,
pidió que no lo esperaran para el té.

"`Adelante,`" dijo la señora Allen, cuando Harriet, en su usual forma escandalosa,
abrió la puerta de golpe, y después se alejó apresuradamente,
casi tumbando a su hermana y a Gertrudis que estaban justo detrás de ella,
y a punto de seguirla a la habitación.

"`Adelante, digo,`" repitió la señora Allen,
haciendo valer su orden al levantarse de su silla y al acercarse a la puerta,
con el fin de llevar a las pequeñas niñas hacia la señorita Robson.
Al haberlas presentado por su nombre,
y a Gertrudis como "`la pequeña niña huérfana de la India,
puesta bajo la tutela del señor Allen,`" les pidió que ocuparan sus lugares en la mesa.

Gertrudis obedeció con su acostumbrada serenidad,
y las otras dos con su usual alboroto y ruido.
Tan pronto como se sentaron, un profundo silencio las acompañó;
un silencio como el que se producía a veces en la presencia del señor Allen,
que siempre lo imponía cuando ocurría un comportamiento rudo o insensato,
pero que rara vez ocurría en su ausencia.
No hacer lo que deseaban, era algo tan extraño para Harriet y Charlotte,
que no sabían qué hacer con eso; y, por ende,
como todos los niños descontrolados y egoístas,
que solo se preocupan por sus propios sentimientos, empezaron a ver a la señorita Robson,
y luego verse a sí mismas,
como si estuvieran comparando sus pensamientos con respecto a ella, y luego se reían,
--y, en resumen,
se comportaban tan inadecuadamente que la señora
Allen se encontraba bastante avergonzada de ellas.
Encontrando que sus numerosos gestos, fruncidos de ceño,
y movimientos de cabeza no estaban siendo tomados en cuenta, ella habló en voz alta,
y le dijo a Harriet que "`si no dejaba de comportarse de esa manera,
iba a ser expulsada de la habitación.`" Esta reprimenda produjo algún cambio;
porque Harriet sabía que "`ser expulsada de la habitación`"
nunca sucedía excepto en casos extremos;
y que eso implicaba, no solo salir de la habitación, sino generalmente ir a otra,
que era la oficina de papá,
donde sabía que recibiría sin duda alguna una reprimenda
más severa de la que su mamá acostumbraba dar.
No había nada que Harriet y Charlotte temieran o respetaban (en cierto grado)
más que las reprimendas de su papá. Y siempre que el señor Allen hablaba,
se dirigía al corazón y a la consciencia, y ellas entendían lo que él quería decir,
y se sentían profundamente humilladas por la conciencia de merecer la reprensión.

Durante el tiempo en que ellas se habían comportado tan inapropiadamente,
la señorita Robson se había estado familiarizando con la pequeña Gertrudis,
en quién observó un suave semblante y gentiles modales que le llamaban la atención,
y que le hizo considerar con menos preocupación de la que normalmente tendría,
el mal comportamiento de sus compañeras.
"`Por lo menos, aquí,`" pensó para sí misma,
"`¡puedo aspirar a tener una alumna que me dé algún fruto por mis labores!`"
La buena dama tampoco se desanimó por lo que observó en las otras dos niñas;
porque percibió inmediatamente,
a partir de la forma en que Harriet entró por primera vez a la habitación,
y por el hecho de que su madre se vio obligada a
hablarle dos veces lo que deseaba de ella,
e incluso a levantarse de su asiento para obligarla a obedecer en esa ocasión,
que estas pobres niñas se encontraban bajo la más
severa de todas las desventajas--es decir,
la de que se les permitiera salirse con la suya, y no obedecer cuando eran corregidas.
No era la primera vez que la señorita Robson tenía que lidiar con niñas como éstas;
y cuando ella consideraba lo jóvenes que eran,
y la esperanza de que aún no hubieran pasado la edad de ser sometidas a un control adecuado,
solo la hacían sentir deseos más fuertes y suspiros más fervientes
en su corazón hacia el Padre y Dador de toda Bondad,
para que, con la ayuda de Su sabiduría y poder,
ella pudiera ser un instrumento para rescatarlas de su actual condición peligrosa.

