== Capítulo III. El Salón de Clases.

Como hemos mencionado,
desde que Gertrudis vivía en Woodside (el pueblo donde el señor Allen vivía,
y donde él era pastor) en la casa había muy poco que tuviera que ver con el estudio,
el aprendizaje o la enseñanza.
Por lo tanto,
fue algo nuevo para ella haber sido convocada a las nueve en punto de la mañana,
al día siguiente de la llegada de la señorita Robson,
a fin de que llevara su pizarra y sus libros de escuela a la habitación que hasta
la fecha se había conocido por el nombre de "`sala de juegos,`" pero que era
ahora iba a ser honrada con el título "`el salón de clases.`"

Como era imposible esperar a que Harriet y su hermana reunieran todos sus libros esparcidos,
se arreglaran su cabello y sus vestidos,
y al mismo tiempo obedecer al señor Allen que las llamaba al pie de las gradas: "`niñas,
la señorita Robson está esperándolas,`" Gertrudis bajó sola,
con sus libros y su pizarra en mano.

Fue recibida amablemente por la señorita Robson,
quién le preguntó acerca de sus conocimientos en ortografía y gramática.
Descubrió que eran mínimos, pero esto se debía más a cierto retroceso en su aprendizaje,
que a la falta de voluntad para trabajar.

"`Bien, debemos esforzarnos para recuperar el tiempo perdido,`" dijo la señorita Robson,
mientras le asignaba algunas palabras de ortografía
para que se las aprendiera de memoria.

Treinta minutos después de las nueve, Harriet y Charlotte finalmente llegaron,
haciendo mucha bulla y ruido, empujándose mutuamente para llegar a sus asientos.

"`Me sentaré ahí, Charlotte,`" dijo Harriet, "`soy la mayor,
y tengo el derecho de escoger mi asiento.`"

"`Siéntate aquí,`" dijo la señorita Robson,
señalando calmadamente el banquillo que estaba a su lado.
Harriet permaneció en silencio, algo asombrada por la serena conducta de su institutriz,
pero evidentemente estaba decidida a discutir el
asunto antes de renunciar a su propia voluntad.

"`Cuando la señorita Singleton estaba aquí,
solía sentarme donde Charlotte está,`" respondió.

La señorita Robson no respondió, sino que volvió a señalar el banquillo,
del que parecía que no había forma de escapar.
Y Charlotte, que se sentía triunfante por el hecho de quedarse en su asiento,
veía todo esto de una manera que Harriet entendía bastante
bien--expresando claramente que creía que sería muy divertido
ver a Harriet envuelta en una discusión con la nueva institutriz.
Por lo tanto, aunque sólo fuera para decepcionar las expectativas de Charlotte,
le pareció conveniente terminar el asunto obedeciendo; y así lo hizo,
aunque tan en contra de su voluntad, que se le salieron las lágrimas,
y apenas pudo esconderlas.

Ahora, queridos niños,
estoy consciente de que estos sentimientos que estoy revelando son muy feos;
pero al mismo tiempo, si son honestos al examinar sus propios corazones,
me temo que algunos se verán obligados a decir que han visto algo muy similar en ustedes.
Es debido a estos sentimientos feos que experimentamos en nuestra niñez,
que conocemos la veracidad de esa solemne descripción de la naturaleza humana caída,
dada a través de la boca del Dios mismo (Génesis 8:21):
"`porque la imaginación del corazón del hombre es mala desde su juventud.`"^
footnote:[RV1602]

Pero bendito sea Su santo nombre, porque,
aunque somos esas criaturas malas desde nuestra juventud, Él no nos ha dejado sin ayuda.
Nos ha prometido un corazón nuevo, un nuevo espíritu,
y uno que nos permitirá vencer con el bien el mal; porque es un Espíritu bueno y bendito,
Su propio Espíritu de verdad, que es ofrecido a todos los que lo piden.
(Mateo 7:7-12.)

Los conocimientos escolares que Harriet y Charlotte
tenían eran más amplios que los de Gertrudis,
pero eran tan desordenadas que esto resultaba ser de poco valor.
Sus libros de texto tenían muchos borrones y estaban desorganizados,
y la portada estaba decorada tanto dentro como por fuera con sus respectivos nombres,
Harriet Allen y Charlotte Allen, en toda clase de letras,
y acompañadas con varios dibujos de caballos, perros, vacas, leones, etc.,
que exhibían claramente la ociosidad que había estado
presente incluso en sus esfuerzos por aprender.

"`Sería bueno mencionar, de una vez por todas,`" dijo la señorita Robson,
"`que nunca permito que hagan
garabatos en los cuadernos o en los libros de ejercicios.`"

"`A la señorita Singleton no le importaba eso,`" dijo Harriet atrevidamente.

"`Quizás no,`" respondió la señorita Robson; "`pero no soy la señorita Singleton.`"

Luego, la institutriz les leyó y le entregó a cada una de ellas una pequeña tarjeta,
donde estaban las lecciones impresas de todos los días,
y el horario en el que éstas debían aprenderse y repetirse.
Una vez hecho esto, continuó la lección de la mañana.

Pero Harriet, sintiéndose irritada debido a lo que había sucedido al entrar en el salón,
y desconcertada y perpleja por el hecho de no saber cómo lidiar con la tranquila,
y firme manera de ser de la señorita Robson,
decidió que no se sometería
ante semejante régimen sin antes intentar resistirse,
y establecer su usual hábito de hacer prácticamente lo que le placía con los
que no querían tener la molestia de enfrentarse con su temperamento rebelde.
Así pues, comenzó a debatir todo lo que la señorita Robson les había encargado.
Reclamó diciendo que no solía hacer su práctica de
Francés a esa hora con la señorita Singleton;
ni su gramática a esa otra.
No repetía tampoco las preguntas de Mangnall en ese día,
ni la historia de Goldsmith en ese otro.

"`Bueno, mi querida,`" dijo la señorita Robson, "`¿qué tengo que ver yo con eso?
Te repito que no soy la señorita Singleton.`"

Su extrema frialdad solo añadió más furia y necedad a la pobre Harriet.
Oh, realmente era una pobre en ese momento; porque al acalorarse más y más con enojo,
prosiguió con su discurso impertinente hasta que, cuando finalmente terminó,
estaba incluso llorando, aunque nadie sabía por qué.

No solamente es triste y pecaminoso ceder a los sentimientos coléricos y malvados,
sino que también es muy humillante.
Por lo general las personas hacen el ridículo ante los ojos de sus semejantes,
cuando permiten que un temperamento furioso los domine.
Tal era el caso, en ese momento con la pobre Harriet--porque verdaderamente,
hizo un espectáculo muy triste de sí misma ante los ojos de los que estaban presentes;
especialmente al ver que la señorita Robson, a quién dirigía toda su furiosa insensatez,
permanecía sentada tan quieta como una estatua mientras ella se desahogaba.
Y cuando Harriet acabó, estallando en lágrimas,
la señorita Robson sólo le señaló con absoluta tranquilidad:
"`Será mejor que salgas a caminar por el jardín, mi querida,
hasta que sientas que puedes continuar con tus lecciones.`"

Su indiferencia aumentó la confusión y la ira de la desorientada niña; que,
habiendo calculado (o, más bien,
calculado mal) implicar a su nueva institutriz en una discusión--como
tenía la costumbre de hacerlo con su madre y con la antigua institutriz,
cada vez que quería salirse con la suya--se vio completamente frustrada
con este modo de conducta que era tan nuevo como desagradable para ella.
De modo que estaba totalmente abrumada en sus emociones,
y sollozaba tan intensamente que tanto Charlotte
como Gertrudis se unieron a su llanto en solidaridad.
Sin duda alguna era una escena muy extraña, observar a las tres niñas llorando,
y ¡ni una de ellas comprendía la causa de sus lágrimas!
Pero la señorita Robson lo sabía; y, a decir verdad,
se había encontrado con algo parecido en muchas ocasiones anteriores,
cuando trataba con niños de temperamentos iracundos.

Se sintió realmente apenada por la forma en que Harriet se estaba avergonzando;
pero tenía la certeza de que la única manera de beneficiarla realmente era permitiéndole
ser su propio reprensor al dejarla sentir la vergüenza y el dolor que los malos
temperamentos traen natural y necesariamente a los que se dejan llevar por ellos.
La tomó de su mano, y dirigiéndola hacia una parte del salón donde había una mesita,
colocó un banquillo allí, y le pidió que se sentara y se tranquilizara,
y cuando se sintiera dispuesta, que regresara a sus lecciones.
De momento, Harriet se opuso a este consejo;
haciéndose ver más culpable y aún más ridícula,
al apartar la mano de la señorita Robson cuando le señalaba el asiento que debía tomar,
y sollozando dijo:
"`¡no lo haré!`"--como podría haber dicho el pequeño Johnny si le fuera posible hablar;
pero que era bastante vergonzoso que proviniera de la boca de una niña de once años.

"`Si no decides sentarte, entonces debes permanecer de pie,`" dijo la señorita Robson;
"`porque no puedo perder más el tiempo hablándote de esto.
Solamente creo que sería mejor para ti que hagas lo que se te pide.
Vamos, cede ante lo que es para tu propio bien.
Dentro de un cuarto de hora, te alegrarás de haberlo hecho.`"

Sollozando aún, pero con menos intensidad, Harriet se sentó, y la señorita Robson,
le puso su mano suavemente sobre su hombro, y le dijo: "`Ahora,
pronto podrás seguir con tus lecciones;`" e indicándole
dónde debía comenzar a copiar del libro,
regresó donde sus otras pupilas, cuyas lágrimas también se habían borrado.

El silencio más absoluto reinó por algún tiempo.

Luego de que esta lucha por el poder había terminado tan desastrosamente,
Harriet al fin continuó trabajando con su asignación, dándose cuenta de que,
desde cualquier punto de vista, era mejor someterse a la voluntad de su institutriz;
y habiendo terminado su lección, para el agrado de la señorita Robson,
se le permitió volver a su lugar en la mesa con las otras niñas,
donde se comportó de una manera muy ordenada y apropiada por el resto de la mañana.
Cuando la escuela terminó, sus cargas y aflicciones fueron olvidadas;
porque la angustia nunca dura mucho en los corazones jóvenes.

"`La lágrima que recorre la mejilla del albor,

Es como la gota de rocío en la flor;

Cuando la nueva brisa de verano se acerca,

Y agita el arbusto, --la flor se seca.`"^
footnote:[Walter Scott.]

Se podría haber esperado, tal vez,
que la señorita Robson hubiera aprovechado la oportunidad
(al concluir la lección de la mañana),
de conversar con Harriet acerca de su inapropiada conducta al inicio de la lección; pero,
a parte del hecho de que ella siempre era una mujer de pocas palabras,
creía que era mejor que las niñas aprendieran lo
más que pudieran a partir de hechos y circunstancias,
en lugar de discursos formales y establecidos.
Estaba segura de que,
como consecuencia de la humillante situación a la que su
propio temperamento colérico e incontrolado la había llevado,
Harriet había aprendido ese día una lección más pesada y
duradera que cualquier otra que hubiera aprendido antes.
Y, de hecho, era evidente,
por su comportamiento hacia su institutriz en lo que restaba del día,
que también era una lección que la había convencido de que,
quienquiera que ella esperara frustrar o confundir en la tarea de disciplinarla,
la señorita Robson no sería la persona apta para ese fin.

