== Capítulo IV. Reprensión y Corrección.

Al cabo de un mes, desde que la señorita Robson llegó a la casa,
se produjo un gran cambio favorable en el ambiente de ese lugar.
Tanto Harriet como Charlotte se volvieron más ordenadas
y obedientes en su forma de comportarse,
y mejoraron tanto bajo la guía de su nueva institutriz,
que la señora Allen ya no interfería (como había tenido el hábito
de hacerlo) en los planes trazados para su educación.

Asimismo, Gertrudis se benefició de esta situación. No era una niña muy lista,
pero sí muy diligente, y al ser (como ustedes ya lo han notado) extremadamente tímida,
su progreso en la escuela se había visto obstaculizado hasta ahora,
debido a la falta de paciencia que ella había encontrado
en quienes anteriormente se encargaban de su educación;
que, debido a la condición delicada de salud de sus padres (y posteriormente,
su fallecimiento),
había sido principalmente responsabilidad de los diferentes sirvientes
que estaban a cargo de ella antes de que llegara a casa del señor Allen.
Estas personas no estaban muy acostumbradas a la
tarea de manejar la ignorancia de la juventud,
ni a esperar pacientemente por el desarrollo de sus destrezas mentales.
De hecho, es de lamentar,
que muchos de los que están más capacitados (por
su formación educativa) para tratar con mentes jóvenes,
aún así carecen de ese principal y gran requerimiento
para poder guiarlos e instruirlos apropiadamente,
que consiste en comprender a fondo, y en obedecer constantemente,
ese precioso mandamiento de nuestro bendito Redentor,
"`con vuestra paciencia ganaréis vuestras almas.`"^
footnote:[Lucas 21:19]

Pero la señorita Robson no era una de éstas.
Ella había sido profundamente ejercitada en diversos tipos de aflicciones;
y a menudo solía decir,
que en la necesidad de ganarse la vida sobrellevando los temperamentos y los hábitos
de los niños en la ardua labor de su docencia (que muchas personas considerarían fastidiosa),
había sido para ella una de sus mayores bendiciones.
Porque, dijo,
que la sacó (por así decirlo) de sí misma y de sus
propios intereses y sentimientos particulares,
y la obligó a cambiar muchos lamentos innecesarios
y consideraciones vanas sobre tal u otra decepción,
por la provechosa tarea, no solo de enseñar, sino también de ser enseñada.
"`La verdad es,`" decía con frecuencia,
"`que he aprendido más cosas valiosas de mis estudiantes,
que lo que ellos han aprendido de mí. Son muchas las valiosas lecciones de paciencia,
dominio propio y el conocimiento de cómo opera el corazón humano,
que ellos me han enseñado sin saberlo.`"

Por lo tanto, pueden estar seguros,
de que ella no era una persona que sintiera algún tipo de impaciencia
o decepción con los grandes esfuerzos que Gertrudis hacía por alcanzar
lo que las otras niñas podían hacer sin esfuerzo alguno.
Porque Harriet y Charlotte eran sorprendentemente
rápidas y ágiles en su capacidad para aprender,
y no les faltaba nada excepto la diligencia que Gertrudis poseía para convertirse,
en su debido tiempo, en niñas bien educadas y con buenas cualidades.

Como les había comentado, dejaré que las personas y las cosas se describan por sí mismas;
por ende, creo que debo compartirles una pequeña escena del salón de clases,
que sucedió dos meses después de la llegada de la señorita Robson,
y que servirá para mostrarles cómo la naturaleza de estas niñas operaba tanto en ellas,
como en su relación de la una con la otra; y también,
cómo influyó la conducta de la institutriz sobre ellas en esa ocasión. Gertrudis
casi siempre lidiaba con un asunto en ortografía que la desconcertaba mucho;
y era identificar cuándo debía hacer el uso correcto
de la consonante '`h`' en ciertas palabras como hay,
ay,
o ahí. Este tema ha resultado ser desconcertante para mentes más maduras que la de Gertrudis,
por lo que la señorita Robson atendía con suma paciencia los frecuentes
errores que ocurrían con el mal uso de esa letra.
Pero no sucedía lo mismo con Harriet y Charlotte,
quienes acostumbraban a reírse entre sí,
y algunas veces susurraban al oído de Gertrudis antes de que iniciara su clase de ortografía,
diciendo:
"`no olvides colocar bien la letra '`h`',`" de una manera
que resultaba bastante molesta para la pobre niña. Y,
a decir verdad, era la mirada pícara y rápida de Charlotte,
mientras Gertrudis repetía su lección, que a menudo la desconcertaba tanto,
y que originaba los mismos errores que ella estaba esforzándose por evitar.

Una mañana, cuando esto ocurría, la señorita Robson lo notó;
y cuando Gertrudis había terminado de decir su lección de ortografía,
y había sido corregida nuevamente en su típico error de
colocar incorrectamente la letra '`h`' en las palabras hay,
ay, o ahí, le dijo a Charlotte:
"`Creo que ahora puedes escribir lo suficientemente bien como para que tomes tu pizarra,
y acompañes a tu hermana en su ejercicio de dictado.`"

Con gran entusiasmo (como suelen mostrarse los niños cuando se proponen algo nuevo),
Charlotte no tardó en tomar su pizarra, y se sentó a la par de Harriet para escribir,
mientras la señorita Robson les leía un pasaje que escogió con un propósito específico.
Y como es un pasaje muy valioso, del cual se puede extraer una gran instrucción,
lo transcribiré para su beneficio; sólo les diré que fue escrito hace dos siglos,
por un hombre sabio y bueno a sus hijos, durante un tiempo en el que,
debido a varias circunstancias, se vio obligado a permanecer separado de ellos.
Por lo tanto, este hombre,^
footnote:[Isaac Penington (1616-1679)]
como un tierno padre,
se propuso exhortarlos por medio de una carta en relación con diversos temas que,
debido a la ignorancia e imprudencia de la juventud,
podían encontrarse en condiciones de ser advertidos.

"`Recuerden esta única cosa`" dijo,
"`que como padre los amonesto y les encargo que tomen nota y observen:
No se critiquen ni se culpen unos a otros o se quejen unos de otros,
por lo malo que observen unos de otros.
Sino más bien, primero tomen nota de lo malo en sí mismos,
y si por la luz verdadera encuentran sus propios corazones limpios de ello,
bendigan a Dios quien lo ha hecho,
y manténganse vueltos hacia Su luz y testigo en ustedes por medio de lo cual Él lo hizo,
y miren que no sean vencidos por eso en el futuro.
Pero si son culpables de este mal, o han hecho últimamente lo mismo,
o es probable que lo hagan de repente, entonces, ¡ay,
absténganse de acusar o culpar a otro!
Esperen en Él en el temor de Dios y oren a Él para
que sean librados y se mantengan fuera de eso.
Luego, en tierna compasión,
amor y mansedumbre adviertan a su hermano o hermana de su mal y
vigilen para ser útiles para preservarlos o restaurarlos.
Oren a Dios para que los dirija cómo ser útiles para ellos.

Porque es el espíritu y la naturaleza del mal (que Dios
castigará) lo que siempre está listo para acusar a otros,
y por muy mala y culpable que sea, se excusará a sí mismo,
pondrá la culpa sobre los demás o recordará alguna otra falla de otro,
cuando debería ser sensible y estar avergonzado de lo suyo.

Queridos hijos, si ustedes inclinan sus mentes para aprender estas cosas,
el Señor los ayudará en ellas, se convertirá en su maestro,
guía y protector y derramará Sus bendiciones sobre ustedes.
En esto serán un consuelo para mí y su madre,
y un honor a Su Santa Verdad y Él también puede darme instrucciones
sabias y paternales para enseñarles más. Pero si son descuidados,
necios, vanos y siguen sus propias mentes y lo que se levante ahí del malvado,
afligirán mi corazón y provocarán a Dios en su contra, a traer el mal sobre ustedes,
tanto en este mundo como para siempre.`"

Cuando Harriet y Charlotte terminaron de escribir este texto,
dejaron de lado sus pizarras hasta que la señorita Robson pudiera corregirlas,
cosa que siempre hacía antes de terminar la escuela;
y luego siguieron con Gertrudis en sus otras tareas matutinas.

Concluyeron su trabajo escolar a la hora habitual,
y de acuerdo con la regla establecida por su institutriz,
estaban saliendo del salón de clases en silencio,
con Harriet (como la mayor) a la cabeza.
Pero, para su sorpresa, se les pidió a ella y a su hermana que se quedaran,
y se le pidió a Gertrudis que saliera sola.

"`Quise que se quedaran,`" dijo la señorita Robson,
"`porque encontré tantos errores en sus pizarras, especialmente en la de Charlotte,
que no quería exponerlas al señalárselos frente a la pequeña Gertrudis;
sobre todo porque estoy segura de que, viendo ahora lo propensas que son,
a pesar de todas sus muchas ventajas, a cometer errores de ortografía al igual que ella,
en el futuro no serán tan rápidas y severas con ella por los errores que cometa.`"

Luego, la señorita Robson les señaló las palabras que estaban mal escritas.
Había más errores en la pizarra de Charlotte que en la de Harriet,
porque en el afán y la impaciencia con que se apresuraba a realizar su nueva tarea,
estaba menos atenta que su hermana; pero el trabajo de Harriet aún reflejaba descuido,
y vale la pena mencionar que, en ambas prácticas,
habían colocado incorrectamente la letra '`h`'. Ambas se sintieron profundamente humilladas,
no solo porque se les hizo ver su tendencia a cometer errores,
sino también por la forma en que fueron reprendidas por su conducta grosera hacia Gertrudis.
Ellas no eran (como les mencioné anteriormente) niñas insensibles; todo lo contrario,
sólo que, hasta hace poco,
sus sentimientos no habían sido guiados o controlados adecuadamente.
El mal y el bien, como las malas hierbas y las flores, habían crecido juntas;
y (¡ay!) como la maldad en la naturaleza caída del
hombre brota mucho más rápido que el bien,
eso que debió haber sido desraizado,
había crecido en exceso y ahogado los brotes de la mejor parte.

Harriet tomó su pizarra en silencio; y con el rostro bastante sonrojado,
se sentó en su escritorio para realizar las correcciones del ejercicio.
Pero Charlotte, quién, aunque era muy temperamental, era una niña muy cariñosa,
y alguien que se había apegado mucho a la señorita Robson,
se sintió reprendida de una manera que la afectó profundamente,
más de lo que se puede describir.
Ella también tomó su pizarra y se sentó en su escritorio;
pero no para corregir inmediatamente su ejercicio, sino que, en lugar de eso,
se puso a pensar en lo diferente que era de Gertrudis; quién (estaba muy segura),
no se burlaría de ella en la humillante condición en que se encontraba,
aunque ella misma se había burlado y complacido con los errores de ortografía de Gertrudis.
También pensó que la señorita Robson había actuado muy amable con ella,
¡cuando pudo haberla expuesto bastante delante de Gertrudis!

Mientras estos pensamientos pasaban por la mente de Charlotte,
Harriet después de corregir los errores,
llevó su pizarra a la institutriz y le pidió permiso para ir donde Gertrudis
al jardín. Tan pronto como Charlotte se encontró a solas con la señorita Robson,
se acercó a ella conmovida, y con dificultad para articular, expresó: "`Oh,
señorita Robson, ¡qué niña más mala soy! ¡Qué corazón más malo tengo!`"

"`Todos tenemos corazones malos, mi amor,`" respondió la señorita Robson,
tomando amablemente su mano, y haciéndola sentarse a su lado;
"`Todos tenemos corazones malos Charlotte, hasta que Dios nos da uno nuevo.`"

"`Oh, me temo que nunca, nunca--,`" aquí,
sus sollozos le impidieron terminar lo que quería decir.

"`Desde luego que nunca te darás ni te harás uno bueno,`" dijo la señorita Robson,
"`si es eso lo que temes.
Pero '`pedid, y se os dará; buscad, y hallaréis; llamad,
y se os abrirá.`' Dios es el que da un corazón nuevo.
Mira, permíteme leerte esta preciosa Escritura;`" y tomando su Biblia,
que siempre estaba presente en la mesa de la escuela, leyó de Ezequiel 36:26-27,
estas palabras: "`Os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros;
y quitaré de vuestra carne el corazón de piedra, y os daré un corazón de carne.
Y pondré dentro de vosotros mi Espíritu, y haré que andéis en mis estatutos,
y guardéis mis preceptos, y los pongáis por obra.`"

"`Ahora, querida niña, en este momento,
el Señor está llevando a cabo esta misericordiosa promesa en ti.
Él está suavizando, o quitando el corazón de piedra, duro y egoísta, que,
por un mal chiste, o un disfrute inapropiado,
a menudo te ha hecho menospreciar los sentimientos de la pobre Gertrudis.
Me atrevo a decir, que preferirías sufrir cualquier dolor en este instante,
que burlarte de ella por sus errores en ortografía, ¿cierto?`"

"`¡Oh, sí! No volveré a burlarme de ella de nuevo.
¡Mi querida Gertrudis!
Oh, ¡si tan solo fuera tan buena como Gertrudis! ¡Ella nunca se burla de nadie!`"

"`Ustedes son diferentes en naturaleza, mi querida.
Gertrudis es una niña increíblemente tímida, y reservada.
Tú eres entusiasta, impulsiva e intrépida.
Pero ¿qué es lo que te hace ser diferente en este momento?
¿Por qué estás actuando ahora contrario a tu naturaleza?`"

Charlotte permanecía en silencio,
pero se quedó profundamente pensativa ante esta pregunta;
y la señorita Robson no interrumpió la pausa hasta
que ésta se extendió un poco más. Entonces se levantó,
y tomando a Charlotte de la mano, repitió con gran solemnidad la promesa de la Escritura;
"`Y pondré dentro de vosotros mi Espíritu.`"
"`Este Espíritu que sientes, es mejor que el tuyo, cariño`" dijo;
"`es ese bendito Espíritu que el Señor nos promete aquí, y nos manda pedir;
indicándonos con ternura que nos será dado si tan solo lo buscamos sincera y verdaderamente.
'`Pues si vosotros, siendo malos,`' dice, '`sabéis dar buenas dádivas a vuestros hijos,
¿cuánto más vuestro Padre que está en los cielos dará buenas
cosas a los que le pidan?`' ¡Cuánto más! Oh,
Charlotte, ¡qué clase de palabras son éstas! ¡Cuán acogedoras! ¡Cuán tiernas!
Pide, entonces y se te dará.`" Luego, habiéndola besado tiernamente en la mejilla,
la señorita Robson salió del salón; y Charlotte, una vez que se tranquilizó,
corrigió su ejercicio, y luego se reunió con su hermana y con Gertrudis,
a quienes encontró sentadas bajo una pérgola en el jardín.

Sus actividades durante las horas de juego generalmente
eran tales que separaban a estas jóvenes en lugar de unirlas.
De hecho, ambas hermanas,
por su similar afición a los juegos activos se encontraban
más a menudo en compañía de la otra que con Gertrudis,
cuya constante satisfacción en su muñeca y su cuna era tan aburrida para sus inquietos
espíritus que rara vez permanecían mucho tiempo en su compañía. Pero esa mañana,
Harriet, al salir del salón de clases,
se fue a la pequeña pérgola donde Gertrudis usualmente
se retiraba con sus pequeños tesoros;
y de una manera muy diferente y dulce, preguntó si podía jugar con ella.
La pequeña niña estaba bastante sorprendida,
y temiendo de que este amable comportamiento fuera el resultado de alguna broma camuflada,
respondió con cierta cautela, "`sé que no te gusta jugar con muñecas, Harriet.`"

"`Oh, en realidad sí me gusta, Gertrudis,`" respondió la otra, "`he estado pensando,
que no siempre soy tan amable contigo como debería; ni tampoco Charlotte.
Y tu siempre eres muy amable con nosotras.`"

Gertrudis miró a Harriet por algunos segundos mientras decía esto,
y creyó poder ofrecerle alguna respuesta.
Pero Gertrudis no era para nada elocuente.
Ella siempre sentía más de lo que podía expresar con palabras,
y al ver que en esa ocasión sus palabras no estaban a su disposición,
expresó el significado de sus pensamientos rodeando con sus brazos el cuello de Harriet,
y besando tiernamente su mejilla.

Harriet, por el contrario, era una gran conversadora;
y no tenía ninguna dificultad para expresar sus sentimientos,
que ahora la movían a decir cuánto lamentaba cada momento
en que había sido descortés con su joven amiga,
y a prometerle que evitaría serlo en el futuro.
Como muestra de su sinceridad, tomó la muñeca de su cuna,
con un cariño como si la misma Gertrudis lo hubiera hecho;
y pronto se vio cautivada y entretenida, al igual que su compañera,
en los asuntos relacionados con su cuidado.

Así estaban jugando, cuando vieron que Charlotte llegaba al jardín para acompañarlas.
Al verla, Gertrudis reaccionó casi instintivamente,
metiendo la muñeca en la cuna y a ambos juguetes bajo la banca en donde estaba sentada,
para proteger a sus preciadas posesiones del peligro.

"`Oh, Charlotte no va a molestarte esta mañana,`" comentó Harriet,
tras haber observado esta rápida maniobra, y estando muy consciente de por qué lo hizo.

Gertrudis no se sentía tan segura de eso como para retomar su actividad,
hasta que la misma Charlotte,
con gran amabilidad y un buen ánimo a los que no podía resistirse,
rogó que la incluyeran en el grupo;
y al escuchar de parte de Harriet que otra muñeca añadiría bastante a su diversión,
salió corriendo muy contenta a buscar la suya, con la que no tardó en regresar,
habiéndole colocado todos los artículos de su vestuario y que pudo reunir rápidamente.

Al principio Gertrudis se sorprendió de tan inusual atención,
pues se había acostumbrado a tener que enfrentarse
con la desatención o incluso con algo peor que eso;
pero como las mentes jóvenes rara vez se cuestionan las causas de esta u otra circunstancia,
sino que se conforman con el momento presente y con la cosa
presente (siempre y cuando les produzca satisfacción),
pronto perdió su asombro ante la amabilidad de sus compañeras de juego,
y si se hubiera sorprendido de algo,
habría sido de que no habían estado siempre tan felices y cómodas juntas,
como lo estaban en ese momento.

