== Capítulo V. Culpa y Remordimiento.

Algunos de mis jóvenes lectores,
que me han acompañado hasta aquí en esta pequeña historia, podrían decir:
"`Hemos escuchado bastante de los errores de Harriet y de los de Charlotte,
pero nada de los de Gertrudis.
¿Acaso no fue a veces alcanzada por la tentación de hacer el mal, al igual que ellas?`"
Mi respuesta debe ser que ciertamente lo fue,
aunque su pecado innato se manifestó de una manera diferente a la de ellas;
y como fiel narradora,
creo que ahora es mi deber exponer una transgresión de una índole muy grave,
a la que ella fue llevada en un momento de descuido, por el cruel adversario,
que "`como león rugiente, anda alrededor buscando a quien devorar.`"^
footnote:[1 Pedro 5:8]

Sin embargo, no fue con la apariencia de un león rugiente,
sino con la de una serpiente astuta (que se adaptaba mejor
a su temperamento) que ofreció sus carnadas a Gertrudis.
Pero debo relatarles los hechos.

Ya les he contado que Gertrudis pasaba una gran cantidad de tiempo en la guardería,
pues le encantaba jugar con el pequeño Johnny,
al que también le gustaba que jugaran con él. Entonces,
sucedió que una mañana antes de que empezara la escuela,
que ella salió de su pequeña habitación, que daba a la guardería,
justo cuando Sara había sido llamada por su patrona para que bajara.

"`¿Serías tan amable de quedarte con el bebé un minuto
hasta que yo regrese?,`" dijo Sara;
una petición que Gertrudis estaba lo suficientemente dispuesta a realizar.
Así que tomó su lugar en la alfombra al lado de Johnny,
que estaba sentado allí con un sonajero en su mano, que movía con gran energía,
un tanto peligroso para la cabeza y las manos de la pobre Gertrudis.
Pero, de repente,
sus ojos se fijaron en un azucarero que estaba sobre la mesa cerca de él,
que estaba lleno hasta arriba con terrones de azúcar; e inmediatamente comenzó,
como era su costumbre de dar a conocer su voluntad y sus deseos, a clamar por ellos.

Al inicio, Gertrudis resistió con firmeza sus demandas al repetir, "`¡no,
bebé! ¡No! ¡No!`"
Finalmente, sin embargo, la fuerte tentación comenzó a obrar sobre su imaginación,
como también sobre la de Johnny.
Pensó que no había nada de malo en darle "`¡tan sólo un bocado al pobrecito!`"
Tan pronto como Johnny la vio levantarse y acercarse a la azucarera, y tomar un trozo,
y luego otro,
su deseo de obtener un cubo se hizo más impetuoso
que nunca,--y con el fin de cumplir sus deseos,
no dejó de intentar todo lo que estuviera a su alcance para conseguir uno.
Dio unas palmadas,
y entonó todos los sonidos de "`¡ta! ¡pa! y ¡ma! que a menudo habían sido
admirados o en ciertas ocasiones solicitados por los que lo rodeaban,
y enseguida obtuvo la dicha de comprobar su éxito.
Gertrudis tomó un poquito y se lo dio a Johnny, y aunque esto no estaba bien,
¡ay! no fue el único error que acompañó el asunto.
Porque después de haber pensado que no había nada de malo
en darle un poquito de azúcar al pequeño Johnny,
comenzó a pensar que no había nada de malo en comerse ella un poquito también;
y entonces lo encontró tan agradable,
que pensó que le gustaría guardarse un terrón o dos
en su bolsillo para comérselos más tarde.
Nunca negocien con la tentación, mis queridos jóvenes amigos.
Dudar, es por lo general, ceder ante las insinuaciones del tentador.
Recuerden siempre que no debe haber ninguna negociación con ustedes
mismos cuando estén en contacto con algo que desean tener,
o desean hacer, que conocen bien que no deberían ya sea desear o hacer.
"`¡Huye por tu vida! ¡No mires detrás de ti!`"^
footnote:[Génesis 19:17 NBLA]
Ese fue el consejo que le dio el ángel a Lot, cuando lo sacó de Sodoma;
y tal será el consejo que deben seguir ustedes cuando se vean ante la tentación,
como sucedió en esta ocasión con Gertrudis.

Si en el momento de haber puesto su mirada en el azúcar,
lo hubiera puesto fuera de su vista y de la de Johnny, a fin de huir, (por así decirlo,
por sus vidas), y no hubiera mirado hacia atrás para recordarlo, ¡cuánta culpa, pena,
y remordimiento, hubiera evitado!
Pero ahora, ella había cometido dos errores; el primero,
darle al bebé lo que no debía tener y que iba en
contra de una orden que Sara había repetido a menudo,
de no darle nada de comer; y el otro error, tomar azúcar para sí. Aún debo añadir,
con profundo dolor, un error más,
y de la peor naturaleza--uno que rara vez falta cuando el mal es cometido; y fue,
decir una mentira.

Ella se comió un terrón de azúcar,
y Johnny uno más pequeño,
y se había guardado dos terrones en su bolsillo antes
de que el sonido de los pasos de Sara,
subiendo por las gradas, hiciera surgir una alarma en su corazón. Pero,
se apuró a sentarse en su lugar en la alfombra, al lado del pequeñito,
y se esforzó por ocultar el efecto de una consciencia culpable,
hablándole y entreteniéndole con el sonajero y otros juguetes
que estaban esparcidos alrededor de él.

Pero Johnny,
quien había permanecido en silencio por algunos momentos mientras disfrutaba el azúcar,
habiéndoselo acabado, no iba a dejarse engañar ni con el sonajero, ni con la pelota,
sabiendo que había algo mucho más complaciente a su alcance.
Gertrudis le decía en vano: "`¡Shh, shh! ¡Mira bebé,
mira aquí!`" Lo que quería era azúcar, y nada más; y viendo que no lo podía obtener,
rechazó todos sus juguetes,
y dejó salir un grito tan tremendo justo cuando Sara abrió la puerta, que alarmada,
y sin saber qué había pasado, se apresuró a entrar,
tomándolo y sentándolo sobre su regazo.
El hecho de que ella se sentara cerca del azucarero,
hizo que cesara inmediatamente su llanto; pues, al verlo más de cerca,
intentó estirar sus manos,
y luego daba palmadas y movía su boca de una manera
que explicaba con bastante claridad por qué clamaba.

"`Oh, pequeño travieso,`" dijo Sarah, "`¿es eso lo que quieres?`"
Entonces, recapacitando en que era extraño que él de repente pidiera,
con tanto fervor el azúcar, a menos de que ya lo hubiera probado,
se volvió donde Gertrudis y le dijo: "`Espero, mi querida,
que no le hayas estado dando azúcar.`"
Muy contrario a su usual y gentil forma de hablar, Gertrudis ahora, bastante molesta,
y casi llorando, respondió: "`¡Por supuesto que no! `"

Había algo tan inquietante en su mirada y tono, que Sara sospechó fuertemente la verdad;
y quizás habría continuado sus preguntas de manera que hubiera podido sacarla a la luz,
si no hubiera sido por Charlotte,
que en ese momento entró a la guardería para recordarle
a Gertrudis que la escuela había comenzado,
y que la señorita Robson estaba esperando a que llegara y leyera.
Si alguna vez han observado, queridos jóvenes amigos, en un día de verano,
cómo una nube puede repentinamente aparecer y cubrir el cielo,
oscureciendo y esparciendo espesas tinieblas sobre las cosas, de modo que los árboles,
las plantas,
y las flores apenas parecen verse igual de lo que eran tan sólo un poco tiempo antes,
cuando estaban iluminados por los alegres rayos del glorioso sol;--entonces pueden
formarse una idea (aunque sea una muy vaga) del melancólico cambio que se había
producido en los sentimientos de Gertrudis en esa última media hora.
El sol radiante de su espíritu, ciertamente, se había nublado de repente,
y una intensa oscuridad, como esa que la nube de tormenta esparce sobre un paisaje,
había oscurecido su mente.
Acompañó a Charlotte, como si fuera una delincuente, al salón de clases,
--prestando tan poca atención a los enérgicos comentarios
que su compañera le hacía mientras se dirigían allí,
que al final le preguntó "`si se sentía bien;`" una pregunta común para Gertrudis,
ya que su salud era muy delicada,
y algunas veces se sentía tan indispuesta como para ausentarse de sus estudios.

"`Si te duele la cabeza, Gertrudis,
estoy segura de que la señorita Robson te excusará,`" dijo Charlotte.

¡Ay!
Era un dolor de una naturaleza más grave, el que oprimió a la pobre Gertrudis.
Era el dolor de una consciencia herida, de la cual se dice en las Sagradas Escrituras:
"`El espíritu del hombre puede soportar su enfermedad, pero el espíritu quebrantado,
¿quién lo puede sobrellevar?`"^
footnote:[Proverbios 18:14 LBLA]

"`Yo estoy muy bien,`" dijo Gertrudis entristecida.
Parecía que su propia naturaleza había sufrido un cambio,
y se había vuelto sombría y amargada como consecuencia de ceder ante la influencia
del que está entre "`los gobernadores de las tinieblas de este siglo.`"^
footnote:[Efesios 6:12]

Durante todo el transcurso de la mañana,
no solo se mantuvo completamente en silencio (pues eso era usual de ella),
sino que había una tristeza en su comportamiento tan inusual, que la señorita Robson,
después de haberla interrogado (como lo hizo Charlotte) si se sentía bien,
sintió la seguridad de que algo pesaba sobre su mente
y ocasionaba su cambio de comportamiento.

¡Pobre Gertrudis!
Estaba en un estado que es muy común entre los pecadores,
y uno que debe ser tan temido y evitado como las transgresiones que lo provocan; a saber,
un estado de dureza de corazón. Niños como Gertrudis,
son mucho más propensos a caer en este estado que los de una mente más viva y abierta;
porque al ser extremadamente reservados a la hora
de comunicarse ocasiona que todos sus sentimientos,
ya sean malos o buenos,
se hundan profundamente y permanezcan más tiempo en sus corazones,
que en el caso de aquellos que les dan rienda suelta a sus emociones en palabras.
El maligno, entonces,
que conoce muy bien cuáles de nuestras debilidades y pecados sirven mejor para su propósito,
persiguió a la pobre niña con sus asaltos a través de su orgullo y carácter reservado,
sugiriéndole constantemente que no se preocupara,
pues nadie podía saber lo que había pasado,
y que ella debía encargarse de que nadie se diera cuenta,
al mantenerlo tan cerca como pudiera dentro de su corazón. De este modo,
la llevó a un estado perfectamente adaptado para mantenerla como su cautiva.

Ah, pero ¡era un estado miserable,
y uno del cual Gertrudis nunca había experimentado antes!
En vano intentó seguir a Harriet y a Charlotte al jardín
cuando llegó la hora en que acostumbraba ir al recreo.
En vano intentó aparentar verse alegre y unírseles en sus juegos.
El simple pensamiento de jugar la ponía más triste que nunca.
Se sintió bastante enojada con ellas por haberle pedido que se uniera con ellas,
y luego se alejó en silencio.

"`¡Qué rara que está Gertrudis esta mañana!`" le dijo Harriet a su hermana,
mientras se alejaba de la pérgola.
"`Creo que no se encuentra bien.`"

"`Ella dice que está muy bien,`" dijo Charlotte;
"`y no creo que tenga algo excepto que está de mal humor.`"

"`Gertrudis no suele estar de mal humor,`" dijo Harriet.
"`Iré a preguntarle qué es lo que le pasa.`"

"`Yo también iré,`" dijo Charlotte;
y se apresuraron a donde ella mientras daba pasos lentos y tristes hacia la casa,
y muy gentilmente, le preguntaron a qué se debía su aparente disgusto.

"`No puedo jugar esta mañana,`" dijo,
sin responderles sus preguntas acerca de su malestar.
"`Verdaderamente, no puedo;`" y para evitar futuras preguntas,
se alejó de ellas por segunda vez, y entró a la casa,
dirigiéndose hacia arriba a su propio pequeño cuarto.

Al pasar por la guardería, vio allí a la señorita Robson hablando con Sara;
pero ninguna de ellas le dirigió la palabra,
y se alegró de pasar por desapercibida hasta llegar a su dormitorio.

Debo decirles,
que la razón por la cual la señorita Robson se encontraba en la guardería era,
para preguntarle a Sara (quién acostumbraba a pasar más tiempo con Gertrudis que con
cualquier otra persona en la casa) si sabía de algo que hubiera ocasionado el desagradable
cambio en el comportamiento de la pequeña que había observado esa mañana.

Sara le contó lo que sucedió cuando le encargó el bebé a Gertrudis
en el momento en que su ama la llamó para que bajara;
lo había hecho en el pasado con frecuencia,
con ambos sentados en la alfombra y por ende libres de algún peligro.
Le contó a la señorita
Robson cómo se había demorado más de lo que esperaba;
y que, al regresar, la exigencia del pequeño niño por el azúcar,
la llevó a sospechar que él lo había probado en su ausencia.
También le mencionó, creyendo que era su deber hacérselo saber,
que por la confusión e inusual enojo en la forma en que
Gertrudis respondió cuando fue interrogada sobre el asunto,
la hacía creer que había sido culpable tanto de tomar
el azúcar como de mentir al respecto.

Esto era una noticia muy triste para la señorita Robson,
cuyo amor por sus alumnas era más parecido al afecto
de una madre que a cualquier otro sentimiento;
y que se había encariñado de una manera especial con la huérfana Gertrudis,
no tanto por su condición indefensa al no tener padres,
sino por las encantadoras cualidades que había percibido en la pequeña niña. Pero,
aunque sus sospechas respecto a Gertrudis eran verdaderamente motivo de tristeza,
no le causaban mucha sorpresa.
La señorita Robson estaba bien familiarizada con la naturaleza del corazón humano,
y como conocía la de Gertrudis, sabía que, en este caso,
cualquier desvío del camino de la verdad y de la justicia la conduciría
a un estado de maldad más profundo,
despertando una disposición a la sutileza y al encubrimiento,
que ella percibía como el pecado más peligroso y hostigador de la niña. Fue un poco
consolador para ella saber que Gertrudis no podía ser feliz con una consciencia culpable.
Eso siempre es satisfactorio; porque, después de caer en el pecado,
el mal más temido es rechazar las afrentas de la consciencia,
y asumir un comportamiento ligero y alegre mientras
que algo interno está diciéndonos constantemente,
¿Cómo, pues, has hecho este grande mal, pecando contra Dios?^
footnote:[Génesis 39:9]

Por el resto del día, Gertrudis continuó en el mismo estado melancólico y depresivo.
Por la noche, el señor Allen, quién, antes de adorar con su familia,
solía leer alguna obra biográfica o histórica que consideraba
que podía ser de interés e instrucción para su joven audiencia,
se sentó para cumplir su acostumbrado compromiso, mientras que la señora Allen,
la señorita Robson, y las jóvenes se dedicaban a la costura.
No me atreveré a decir si fue por casualidad,
o si alguna insinuación de parte de la señorita Robson pudo
haber influido en la elección del libro para esa noche;
pero sucedió que después de haber elegido La Vida de Samuel Kilpin,
como el libro que iba a leerles,
no había avanzado mucho antes de llegar a la siguiente anécdota:

"`Cuando tenía siete años,`" dice el señor Kilpin,
"`me dejaron a cargo de la tienda.
Un hombre pasó anunciando, '`¡Corderitos de juguete, todos blancos y limpios,
a un centavo cada uno!`' En mi afán por tener uno, perdí todo el dominio propio,
y tomando un centavo del cajón, hice la compra.
Mi sabia madre, con su agudo ojo, me preguntó cómo obtuve el dinero.
Yo evadía la pregunta con algo como una mentira; y ante los ojos de Dios fue una mentira,
porque oculté la verdad.
El cordero fue colocado sobre la repisa de la chimenea y fue muy admirado.
Sin embargo, para mí era una fuente de inexpresable angustia,
pues continuamente resonaba en mis oídos y corazón, '`¡No hurtarán,
ni mentirán!`' La culpa y las tinieblas se apoderaron de mi mente;
y en una profunda agonía del alma,
me dirigí a un granero (el lugar permanece fresco en mi memoria),
y allí oré y rogué con gemidos que no podían ser expresados,
por misericordia y perdón. Pedí misericordia por amor a
Jesús. Con alegría y entusiasmo dejé el granero,
creyendo y adoptando para mí el pasaje:
'`Tus pecados te son perdonados.`' Me dirigí a donde mi mamá, le dije lo que había hecho,
pedí que me perdonara, y luego quemé el cordero,
mientras ella lloraba por su joven arrepentido.`"^
footnote:[La Vida de Kilpin, pág. 6]

Tan pronto terminó de leer esta conmovedora anécdota, el señor Allen hizo una pausa,
como solía hacer cada vez que se encontraba con algo particularmente interesante.
Luego, cerrando el libro, dijo, "`Creo, queridas hijas,
que les haría un mal si alejara sus mentes de la ejemplar y conmovedora
lección que esta anécdota está diseñada a dejarles,
al continuar leyendo la historia.
En lugar de eso,
me gustaría hablarles un poco de los sentimientos que se han levantado en mi mente.
Primero, deseo dirigir su atención a dos circunstancias registradas en esta historia,
las cuales confieso que me golpearon fuertemente.
La primera es, la condición de la mente del niño cuando entró al granero, y la otra,
el cambio que se había producido en él cuando lo dejó.`"

"`Él dijo, '`la culpa y las tinieblas se apoderaron de mi mente;
y en una profunda agonía del alma, me dirigí a un granero.`' Esto, como pueden observar,
era su triste condición al entrar a ese lugar; pero, cuando lo dejó, ¡qué cambio,
qué bendito cambio había ocurrido! '`Con alegría y entusiasmo,`' dice,
'`dejé el granero.`' Ahora,
no tenemos que preguntarnos qué ocasionó esta feliz transformación,
pues él nos dice que fue el resultado de creer y adoptar el pasaje:
'`Tus pecados te son perdonados.`' No tenemos, digo,
que ocupar nuestras mentes en un intento de investigar o razonar sobre estas circunstancias,
sino que debemos considerar la gran bendición que acompaña
a una confesión de pecado verdaderamente arrepentida.
Todos estamos propensos a caer en tentación. Todos somos criaturas pobres e indefensas,
rodeados por todos lados de las trampas del diablo,
y llevando en nuestros corazones un enemigo traicionero,
que continuamente está listo para escuchar al sutil tentador.
Pero consideren; aunque caigamos en la red que él tiende para nuestros pies,
siempre tenemos el poder de volvernos al Libertador; al amado Redentor, que,
aunque nunca pecó, fue a menudo tentado,
y que tiene una porción de la más tierna misericordia para
dar a todos cuya debilidad es la causa de su derrota.

"`Ahora, la forma en que satanás obra con nosotros es, en primer lugar,
incitarnos a cometer el mal,
y luego endurecer nuestros corazones al presentarnos esta u otra mentira (pues él nunca
puede presentarnos nada excepto mentiras) con el fin de desviarnos y confundirnos aún
más. En ocasiones le dice a un pobre pecador que nadie se dio cuenta de lo que hizo,
y que nadie debe saberlo,
sin tan sólo lo guarda para sí mismo y se mantiene
firme en negar su falta cada vez que se menciona.
Esta es su forma preferida, y (¡ay!) demasiado exitosa de proceder.
Y es su forma preferida, porque mantiene al pobre cautivo aún más atado a sus cadenas,
haciéndole añadir mentira tras mentira, y pecado tras pecado,
hasta que la miserable criatura piense, '`bien puedo seguir pecando,
porque no puedo pecar peor de lo que ya lo he hecho,
pues ya me hice vil ante los ojos de Dios.`' Así es como el corazón se endurece,
hasta que se hunde en esa horrible descripción contenida en estas palabras:
'`Por cuanto sé que eres obstinado, que tu cuello es tendón de hierro,
y tu frente de bronce.`'`"^
footnote:[Isaías 48:4 NBLA]

"`Pero este no era el estado del niño del que les he estado leyendo.
Dichosamente,
él no permitió que el malvado prevaleciera endureciendo
su corazón. Dio el único paso que le correspondía dar,
tras haber caído en el pecado.
Se levantó, como el hijo pródigo, y fue a su Padre;
y el Padre de las Misericordias--como del que leemos
en la parábola--lo recibió con una bienvenida,
una tan gozosa, que toda su culpa y oscuridad, y la dolorosa agonía de su alma, se fue;
y en su lugar, tanto el gozo como el entusiasmo llenaron su corazón. Por lo tanto,
mis hijas, cada vez que el cruel adversario los tiente al pecado,
recuerden el ejemplo de este querido niño. No acudan
a satanás en busca de consejo o consuelo.
Aborrezcan el falso reposo o paz que puedan encontrar en cualquier cosa que sugiera.
No tienes por qué experimentar la tranquilidad o felicidad de mente
mientras su pecado permanece sin ser confesado delante de Dios.
Les aseguro, no tienen derecho a ello.
No les pertenece.
Dios no sería Dios si Él nos permitiera ser felices mientras estamos voluntaria
y conscientemente persistiendo en esas cosas que Él ha prohibido.
¿Qué pensarían de mí, que soy tan solo un simple ser humano,
y un pobre pecador indefenso de la misma naturaleza que la de ustedes; sin embargo,
qué pensarían de mí, si tras haber detectado alguna falta en ustedes, dijera: '`Bueno,
no se preocupen; traten de olvidarla tan rápido como puedan, y, sobre todo,
no se incomoden aún más confesándola; sino que niéguenla con determinación,
y dispónganse a permanecer felices.`' ¿No me despreciarían en sus corazones?
Pero, algo parecido a esto,
solo que infinitamente más degradante (porque se dirige a un Ser infinitamente perfecto)
son los pensamientos que los endurecidos pecadores sostienen con respecto a Dios.
De ahí que leemos en el Salmo 50 que, dirigiéndose a tales personas, el Señor dice:
'`Pensaste que Yo era tal como tú.`'`"^
footnote:[Salmo 50:21 NBLA]

"`Pero existe otro estado, y uno más esperanzador y deseable,
que a veces surge como consecuencia del pecado,
y que fue el estado del querido niño del cual hemos estado leyendo; es decir,
el estado de la gran angustia y remordimiento.
Observen con qué sensibilidad, con qué convicción, habla de ello.'`El cordero`', dijo,
'`fue colocado sobre la repisa de la chimenea y fue muy admirado.
Para mí era una fuente de inexpresable angustia,
pues continuamente resonaba en mis oídos y corazón, ¡No hurtarán,
ni mentirán!`' Fue esta dolorosa agonía del alma que hizo que él se volviera al Ayudador.
Fue tras ceder a las heridas y a los punzones del Espíritu justo,
que lo había afligido y contristado, que todo fue sanado.
Si hubiera endurecido su corazón al resistir las obras de este Testigo
fiel y verdadero--si hubiera decidido no incomodarse por él,
y hubiera persistido en ocultar su pecado--oh,
¡cuán diferente habría resultado toda su vida! ¡Cuán endurecido se habría vuelto! ¡Cuán
impenetrable! ¡Cuán atrevido en la maldad! ¡Cuán desvergonzado en el modo de mentir!
Oh, mis hijas, mis queridas hijas, busquen sobre todas las cosas del Señor,
esa ternura de consciencia que no les permitirá estar felices en ningún camino del mal.
Todo lo que necesitamos cuando hemos caído en pecado y transgresión,
es regresar al Señor nuestro Dios.
'`Tomen con ustedes palabras, y vuélvanse al Señor. Díganle: Quita toda iniquidad,
y acéptanos bondadosamente.`'^
footnote:[Oseas 14:2 NBLA]`"

El señor Allen terminó de hablar,
y se veía profundamente sumergido en sus pensamientos por unos momentos.
Luego, cerrando el libro, y mirando su reloj,
dijo que era hora de que los criados entraran.
Estaba a punto de levantarse y sonar la campana,
cuando un audible estallido de lágrimas de la pobre
Gertrudis atrajo todas las miradas hacia ella.

Estaba de pie, sola, junto al rincón del armario,
donde se había ido para dejar su trabajo en el cajón
que estaba destinado para el uso de los niños;
y allí, de espaldas al resto del grupo, había estado luchando todo el tiempo que pudo,
no contra su "`dolorosa agonía del alma,`" sino, si era posible,
contra no darla a conocer hasta que hubiera entrado en su pequeño
santuario y derramado sus penas delante de su Padre celestial.
Pero sus emociones llevaban demasiado tiempo acumulándose,
y se habían vuelto muy fuertes como para contenerlas por más tiempo.
Apoyó su barbilla en sus manos que puso juntas, y apoyando su frente en el armario,
sollozó como si su corazón se fuera a romper.

Las niñas, y también la señora Allen,
se apresuraron a preguntarle qué era lo que le sucedía,
pero el señor Allen les indicó con un gesto que se detuvieran;
mientras tanto la señorita Robson, con el fin de desviar su atención,
las invitó a mirar unos dibujos con ella.
El señor Allen entonces fue donde Gertrudis, y tiernamente la acercó a él,
sentándose en una silla que estaba cerca, pero de manera que, al situarla frente a él,
la cubrió de la vista de los demás. La calmó con las más amables palabras,
secó sus desbordantes lágrimas con su pañuelo,
y tan pronto percibió que ella podía hablar claramente,
le preguntó la causa de su angustia, pero con una voz tan suave,
que el resto de las personas que estaban en el otro extremo de la habitación,
no pudieron escuchar lo que pasaba.
Sin responder inmediatamente, Gertrudis puso su mano en su bolsillo,
y sacando dos terrones de azúcar, miró su rostro, y nuevamente estallando en lágrimas,
dijo: "`Yo los robé.`"

El señor Allen expresó algunas muestras de preocupación al escuchar esto.

"`Pero estás muy arrepentida por tu error, no lo dudo`", dijo.

"`Oh, ¡sí! --muy--¡muy arrepentida!`"
Dijo sollozando.

"`Y, ¿has confesado tu pecado a tu Padre celestial, Gertrudis?`"
Le preguntó el señor Allen.

"`No podía orar hasta que leíste sobre ese pobre niñito,
señor. Pero desde entonces he deseado estar a solas, para poder hacer lo que él hizo.`"

"`Entonces tu corazón ha orado, querida niña; y Dios mira al corazón,
y ve lo que ocurre allí. Y cuando Él contempla un
sincero arrepentimiento y angustia por nuestras faltas,
Él nos perdona, como un Padre misericordioso.`"

"`Oh, ¡aún no te he contado todo!`" dijo Gertrudis, llorando.

"`Me atrevo a decir que puedo decírtelo,`" dijo el señor Allen.
"`No dudo de que el malvado que te tentó a robar el azúcar,
también te tentó a decir una mentira para esconder tu error.
Cualquier pecado al que él arrastre a una pobre alma,
él se asegura de añadirle una mentira, si no es que ya estaba allí antes.
¿Te tentó a mentir?`"

"`Sí, lo hizo; ¡le dije a Sara una mentira malvada!
Le dije que no le había dado azúcar al bebé, cuando sí lo hice.
Oh, ¡qué mala he sido!`"

"`Bien, mi niña,
agradece que el Señor ha tocado tu corazón con una consciencia de tu pecado.
Tu deber ahora es confesarlo humildemente delante de Él,
y reconocerlo ante esos prójimos a quienes has engañado.
Me atrevo a decir que, estás dispuesta a decirle a Sara la verdad,
y reconocer ante ella lo mal que has hecho.`"

"`Oh, ¡sí! Me encantaría hablar con ella antes de que baje para el tiempo de adoración.`"

"`Ven, entonces, y te llevaré a donde ella;`" y llevándola de la mano,
el señor Allen fue con ella al pie de las gradas y llamó a Sara, que no tardó en llegar.

"`Aquí está una niñita que tiene algo que decirte, Sara,`" dijo;
"`llévatela a la guardería; y en unos cuantos minutos sonaré la campana,
y ambas pueden bajar juntas.`"

Justo cuando Sara regresó a la guardería,
Gertrudis arrojó sus brazos alrededor de su cuello,
y en la medida en que sus lágrimas y emociones se lo permitían,
desahogó su cargado corazón reconociendo su culpa.

Podemos estar seguros de que Sara se apresuró a consolarla,
y en la medida en que ella misma había sido ofendida,
a perdonarla también. Pero Gertrudis sentía que había alguien
mayor que cualquier ser humano contra quién ella había pecado;
y antes de regresar al salón, se fue a su pequeña habitación, y ahí, arrodillada,
desahogó todo su corazón cargado a través de una humilde y sincera confesión de pecado.
Al igual que el querido niño,
cuya conmovedora historia sobre su error y arrepentimiento le había atravesado su alma
de tal forma que ella apenas podía contener sus emociones al escucharla,--ella también
dejó su lugar solitario "`con alegría y entusiasmo.`"
La oscura nube tormentosa que estaba sobre su espíritu se había ido;
y cuando el señor Allen sonó la campana, pudo seguir a Sara hasta el salón,
sintiéndose un ser muy diferente de la pobre Gertrudis, infeliz y llena de culpa,
a la que Charlotte había llamado al salón de clases por la mañana.

