== Capítulo VI. La Madeja de Seda Enredada.

Una de las reglas de la señorita Robson con sus jovencitas era,
que "`cualquier cosa que comenzaran, tenía que ser terminada.`"
Esta era una regla que a menudo resultaba difícil para los
temperamentos inquietos e impacientes de Harriet y Charlotte,
y que a veces también ponía a prueba a Gertrudis,
como tendré la oportunidad de mostrarles en la historia de una madeja de seda.

Un día, Gertrudis estaba empezando a enrollar su madeja,
y le pidió a Charlotte que se la sujetara brevemente.
Charlotte consintió,
con la condición de que la enrollaría en lugar de solamente sujetarla,
lo que Gertrudis aceptó de buenas.
Comenzaron la actividad con mucha alegría,
y más aún porque empezó a caer un aguacero que les impidió salir al jardín,
como solían hacer cuando terminaban la escuela.

"`Oh, qué bonito es esto,`" dijo Charlotte.
"`Me encanta enrollar la seda o el algodón--`" Apenas había dicho esto,
cuando un inesperado nudo en la seda (que con un poco de paciencia
hubiera sido rápidamente soltado) comenzó a probar su temperamento,
haciéndola halar de un lado a otro,
hasta que la había enredado tanto que realmente requería, no solo de más paciencia,
sino también de más sabiduría que la que Charlotte poseía.

La pobre Gertrudis vio con preocupación la peligrosa
condición en que se encontraba su pertenencia;
pues, ya que no podía continuar, Charlotte tomó unas tijeras que estaban sobre la mesa,
e iba a cortar los nudos que no podía desenredar.

"`Oh, querida Charlotte, por favor, ¡no lo hagas!
Dijo Gertrudis, "`si la sostienes, yo trataré de desenredar los nudos.`"

"`¿Tú los vas a desenredar?`"
respondió Charlotte con cierto desprecio; porque, a decir la verdad,
estaba volviéndose tan molesta que necesitaba algo en qué descargar su frustración,
y por eso estaba demasiado dispuesta a desahogarse con Gertrudis.
"`¡No me digas, desenrédalos tú! ¡Creo que el pequeño Johnny también podría hacerlo!`"

A Gertrudis le resultaba siempre más fácil soportar el mal humor que reaccionar ante él,
por lo que no respondió ante tal berrinche,
y estaba al punto de resignarse ante la decisión de Charlotte de cortar la seda,
cuando se abrió la puerta, y la señorita Robson entró a la habitación.

Este fue el final de la obra de destrucción que Charlotte se proponía realizar;
pues esta era una situación en la que sabía que iba
a tener que obedecer la regla de su institutriz,
que cualquier cosa que sus alumnas empezaran, tenían que terminarla.

"`Parece que hiciste un trabajo muy lamentable con
esa madeja de seda,`" dijo la señorita Robson;
"`tráemela, y déjame ver si te puedo ayudar;`" y ella se sentó en su silla.

"`Gertrudis, sostenla tú,`" dijo Charlotte, "`no podemos sostenerla entre las dos,
tú sabes.`"

"`Sí, sí pueden,`" dijo la señorita Robson; "`vengan, y pónganse a mi lado,
y les daré las instrucciones sobre lo que deben hacer; por lo menos, a la que enrolla.
La otra solamente tiene que mantener las manos quietas.`"

Si no hubiera sido la señorita Robson con la que
Charlotte hubiera tenido que tratar en ese momento,
sin duda se habría rebelado, y se habría negado a continuar en esa actividad;
porque ya estaba muy lejos de poder decir (como había
dicho un poco antes) que "`le encantaba.`"
Pero había algo que gobernaba en la señorita Robson, que se hacía sentir,
incluso sin palabras.

Sin embargo, con un gran disgusto, y con lágrimas,
Charlotte entregó la madeja enredada a su institutriz
tal como ella lo solicitó. Y no pudo evitar decir:
"`¡La próxima vez esperaré antes de ofrecerme a enrollar una madeja
de seda!`" un comentario descortés que se vio acompañado con una
mirada igualmente descortés hacia Gertrudis.

"`Pensé que habías dicho, querida Charlotte,
que te encantaba enrollar la seda o el algodón. Si hubiera sabido que te desagradaba,
no te hubiera pedido que lo hicieras,`" dijo Gertrudis.

"`Charlotte es como la mayoría de las personas jóvenes,`" respondió la señorita Robson,
"`se deleitan en las cosas mientras son agradables.
Pero la verdadera forma de ser feliz, Charlotte,
es deleitarse en ellas cuando son desagradables.`"

"`No creo que nadie pueda hacer eso,`" dijo Charlotte.

"`No en el momento, lo reconozco,`" dijo la señorita Robson.
"`Nadie puede deleitarse en las cosas desagradables cuando se sienten así;
pero hay algo que se puede obtener solamente cuando las cosas son desagradables,
y que puede ser ciertamente satisfactorio.
¿Pueden adivinar lo que es?`"

Charlotte permaneció con la madeja enredada colgando de sus manos,
y como no podía o no estaba dispuesta a responder a la pregunta,
se ocupó en tratar de encontrar el extremo adecuado de la seda,
consiguiendo enredarla aún más.

"`Creo que es probable que no le sacarás mucho provecho
a la situación que se nos presenta esta mañana,
Charlotte,`" dijo la señorita Robson, "`de lo contrario,
te diría que ahora mismo tienes la oportunidad de solucionar lo que te trato decir,
y de conocer por ti misma que hay un deleite que
se encuentra en las cosas cuando son desagradables,
algo que no se puede obtener en ningún otro momento, o de alguna otra manera.
Pero, como el aguacero ha terminado,
puedes ponerte tus cosas y unirte a tu hermana en el jardín;
y Gertrudis y yo trataremos de descubrir cuál es el deleite del que les estoy hablando.`"

Al decir esto,
la señorita Robson estaba a punto de tomar la madeja enredada de las manos de Charlotte,
pero la pequeña niña, encontrándose ahora con sentimientos más apacibles y reformados,
y con lágrimas en sus ojos que provenían de una mejor
fuente que las que los inundaban unos minutos antes,
rogó para que le permitiera quedarse,
y compartir con Gertrudis la lección que iba a ser impartida.

El permiso fue concedido de inmediato por su institutriz;
que habiendo colocado a Charlotte (como la que enrollaría la seda)
en la condición más conveniente para recibir sus instrucciones,
procedió a dárselas;
comenzando por recordar a las niñas que necesitarían
mucha paciencia para llevar a cabo su tarea.

"`¡Ah!
Ahora entiendo,`" dijo Gertrudis, con una sonrisa;
"`Ahora entiendo qué es eso que debería deleitarnos,
y que solamente se puede obtener cuando las cosas son desagradables.`"

"`Y yo también,`" dijo Charlotte, sonriendo igualmente.
"`La señorita Robson se refiere a la paciencia.`"

"`Bien,
veamos si podemos encontrar algo de esta preciosa cosa en nuestra actividad,`"
respondió. "`Extiende tus manos tan rectas y quietas como puedas,
Gertrudis; no debe importarte que te duelan tus brazos un poquito,`" dijo; "`y ahora,
Charlotte, empecemos.
Presta atención, debes pasar el cartón de seda debajo de ese hilo--ese hilo,--justo ahí.`"

La orden fue acatada, y se avanzó un poquito;
pero en cada ronda debía pasar el cartón de cierta manera en particular,
y Charlotte casi nunca había experimentado algo tan excesivamente desafiante.
Pues las primeras dos o tres veces,
suspiró profundamente cada vez que llegaba al obstáculo;
pero la señorita Robson la animó repitiéndole, "`Un poco más--tan solo un poco más,`"--y,
avergonzada de que Gertrudis la superara en el asunto
al mostrar más paciencia y perseverancia que ella,
se esforzó grandemente en contener su temperamento,
y lo consiguió hasta el punto de que la seda quedó adecuadamente enrollada,
sin ningún daño.

"`Bueno, eso sí que es satisfactorio!`" dijo Gertrudis,
"`aunque me dolían bastante los brazos, y casi que en una o en dos ocasiones,
tuve que esforzarme para no pedir un pequeño descanso.`"

"`Pero ahora, me atrevo a decir, estás muy contenta de que perseveraste;
¿no es así?`" preguntó la señorita Robson.

"`Sí, lo estoy,`" dijo Gertrudis.
"`Me alegro por dos razones.
Me alegro de que no haya arruinado mi seda al cortarla;
y me alegro muchísimo de haber aprendido lo satisfactoria que es la paciencia.`"

Charlotte.--"`Y yo también lo estoy.
Ahora puedo sentir que en efecto hay satisfacción en ella.
Pero, señorita Robson, no hay otra forma de aprender paciencia que no sea sobrellevando,
o haciendo cosas desagradables?`"

Señorita Robson.--"`Responderé a tu pregunta haciéndote una, Charlotte; y es ésta:
¿Qué es la paciencia?`"

Charlotte.--(Después de una pausa)--"`Creo que es tratar
de mostrarse contenta y feliz cuando estás apunto de llorar;
y quedarte quieta y callada cuando estás a punto de romper todo en pedazos.`"

Señorita Robson.--"`Supongo que me estás describiendo lo
que pasaba por tu mente mientras enrollabas la seda.
Bien, debe ser algo verdaderamente satisfactorio y grato lo que libra a cualquier ser
humano de un comportamiento tan escandaloso y degradante como el que mencionaste;
y me atrevo a decir que también lo piensas así. ¿No
te sientes aliviada de no haber hecho el ridículo,
ni llorando, ni rompiendo la seda en pedazos?
¿No disfrutas de la calma que estás experimentando, y no puedes ver claramente qué pobre,
inmadura, y despreciable criatura te habrías visto, si,
en lugar de permanecer allí tan serena y sonriente
con la seda perfectamente enrollada en el cartón,
te hubieras mostrado con la seda rota en pedazos (para desgracia
y decepción de Gertrudis) y sollozando como una bebé?`"

Charlotte.--"`Oh sí, señorita Robson--no soporto pensar en ello.
Siempre amaré las cosas desagradables,
si ellas me enseñan algo tan bueno como la paciencia.
Pero, aún no veo muy bien, por qué no puedo aprenderla de una manera menos desagradable.`"

Señorita Robson.--"`Qué piensas de eso, Gertrudis?`"

Gertrudis.--"`No creo que nos falte paciencia cuando las cosas son placenteras y agradables.
Supón Charlotte,
que enrollar la seda hubiera proseguido de forma tan bien como cuando dijiste, '`¡Oh,
qué bonito es esto!`' No veo qué oportunidad hubiéramos
tenido para impacientarnos por ello.`"

Charlotte se vio obligada a confesar que se trataba de un argumento de peso,
y a admitir que la paciencia solamente se podía aprender
cuando las cosas iban contrarias a nuestros deseos;
o, como ella lo había expresado, cuando eran desagradables.

Señorita Robson.--"`Creo, entonces,
que he dejado claro mi punto y he demostrado que nos conviene
deleitarnos en las cosas cuando son desagradables.`"

Charlotte.--"`Verdaderamente, nunca he sentido la clase de satisfacción que siento ahora,
habiendo conquistado mi impaciencia con respecto a la madeja de seda.
Pero, señorita Robson,
esto pareciera ser una cosa tan pequeña como para angustiarse o alegrarse.`"

Señorita Robson.--"`Por muy pequeño que sea, Charlotte,
viste que fue casi demasiado para ti.
No debes caer en el error en el que las personas comúnmente caen,
de hablar sobre esto o lo otro como algo '`muy pequeño.`' Nada
es tan pequeño como para no ocasionar algunas consecuencias;
y lo que sea capaz de exaltar tus emociones y de probar tu temperamento,
es algo muy importante, sin importar qué tan insignificante te parezca.
Pero tu error, y el error general de los que hablan de esta manera,
surge al mirar la cosa o acción externa;
y no los sentimientos y efectos internos que la acompañan. Por ejemplo, en esta ocasión,
enrollar una madeja de seda pareciera ser algo muy insignificante,
y podría hacerse sin que fuera necesario decir una sola palabra al respecto.
Sin embargo, ser apresurado e impaciente e irritable e imprudente,
como tú estabas a punto de ser, al hacer esta cosa tan simple, son asuntos muy serios,
mi querida niña,
y solamente conozco un método para proponerte evitar convertirte en su víctima,
y es recordando que todo lo que hagas, debes hacerlo de corazón,
como para el Señor y no para los hombres.
El pensamiento de que esto o lo otro es algo insignificante,
nunca te ayudará a sobrellevarlo con la paciencia adecuada.`"

Gertrudis.--"`¿Entonces, existen dos tipos de paciencia, señorita Robson?`"

Señorita Robson.--"`Hay un tipo de paciencia falsa, Gertrudis,
que a menudo les permite a las personas controlar sus sentimientos, de modo que,
en circunstancias difíciles aparentan ante los demás poseer mucho dominio propio y templanza.
Esto no merece ser llamado bajo el nombre de paciencia,
porque la paciencia es algo santo.`"

Charlotte.--"`¿Cuál es el nombre de esta falsa paciencia, señorita Robson?`"

Señorita Robson.--"`Su nombre es ORGULLO.
¿Saben algo acerca de él?`"

Charlotte.--"`¿De qué manera se expresa?`"

Señorita Robson.--"`Se siente como si fuera mejor morir
antes que mostrarse preocupada ante los demás. Por eso,
como acabas de decir,
trata de aparentar estar contenta y feliz cuando más bien está lista para llorar;
y permanece quieta y callada cuando en realidad desea romper todo en pedazos.`"

Charlotte.--"`Me temo, entonces, que estaba sintiendo algo de esta falsa paciencia;
porque verdaderamente estaba muy indispuesta de que me vieran preocupada,
y no me gustó para nada que Gertrudis mostrara más paciencia que yo.`"

Señorita Robson.--"`Es muy probable, mi querida,
que tu perseverancia tuvo más que ver con el orgullo que con la paciencia.
Debe haber un profundo sentimiento de la presencia de Dios en el corazón,
antes de que podamos llevar a cabo todas nuestras acciones ante sus ojos,
y cada vez que nuestros temperamentos sean probados,
respirar anhelante en busca de Su ayuda y favor.
Sin embargo, es definitivo,
que no se puede encontrar nada de la verdadera paciencia
a menos que sea proporcionada por Él. Porque la paciencia,
debo decírtelo una vez más, es algo santo;
y como a menudo necesitarás que te recuerde de su importancia,
te leeré algunas líneas escritas por un amigo mío, que si te gustan,
te entregaré una copia, y así podrás aprenderlas de memoria.`"

Ambas niñas solicitaron escucharlas,
y la señorita Robson recitó entonces las siguientes líneas:

A LA PACIENCIA

¡Humilde y sumisa Paciencia!
Nacida en el dolor,

Y sin embargo sonríes a través de tus lágrimas; ¡cuán suave e inferior,

y tranquila es tu presencia! ¡Gracia austera!

¡Cuán humilde son los entornos donde tu pálida cara

Revela su meditativa belleza! ¡Profundas las copas

de amargura que calmadamente tomas!

Pues bienvenido es para tu amoroso corazón

En el dolor y la pena tomar la más grande porción;

Y dulcemente tu espíritu gentil da para compartir

De lo que tu Maestro te da para sufrir

¡De Su triste porción! Oh, Tú, Santo,

"`¡Hágase Tú voluntad!`" fue su último lamento

y junto con ese lamento expiró por la humanidad perdida en su consciencia,

¡Permite que mi alma probada encuentre tu santa paciencia!

