== Capítulo VII. Un Paso Adelante en la Narración.

No los detendré, mis jóvenes lectores,
con una narración detallada de las diversas circunstancias y eventos que ocurrieron
en la familia del señor Allen durante los próximos dos años. Pareciera un largo período;
y quizás piensen que sucedió algo lo suficientemente
interesante durante este tiempo para relatarles;
y de hecho, yo podría hacer un libro bastante grande si procediera como he comenzado,
y les relatara los diversos y pequeños asuntos que ocurrieron entre las niñas y su institutriz,
y los otros miembros de la familia,
por el lapso de estos dos años. Pero tengo otras cosas de las que debo contarles,
y por lo tanto debo contentarme con informarles, a grandes rasgos,
que Harriet y Charlotte mejoraron mucho durante este tiempo;
que Johnny se había convertido en un pequeñín enérgico, que corría por toda la casa,
hablando con cualquiera que tuviera tiempo para escucharlo;
y que el señor y la señora Allen, y la señorita Robson,
eran en todos los aspectos (con la excepción de ser dos
años más mayores) prácticamente los mismos que han conocido.
"`¿Pero qué hay de Gertrudis?`"
Me parece que los escucho decir.
"`¿Por qué es que no nos dices nada sobre ella?`"

Por lo general, no estamos dispuestos a comunicar, ni a escuchar,
noticias que puedan considerarse tristes;
y por eso mismo he tardado en decirles que los acontecimientos relacionados con Gertrudis
están más mezclados con tristeza que con el resto de los integrantes de la casa.

Ya les he insinuado que su salud era delicada; y su constitución, naturalmente débil,
había recibido una fuerte sacudida debido a una fiebre que, en el invierno pasado,
había atacado a la mayor parte de la familia,
pero de la que todos los demás miembros se habían recuperado.
Esta fiebre había dejado a Gertrudis con una molestia en la columna vertebral,
que la obligaba a permanecer constantemente acostada, y ya habían pasado varios meses,
en los cuales la pobre niña sólo había sido trasladada de su cama a un
sillón que habilitaron para ella en la guardería. Bajo estas circunstancias,
por supuesto,
no podía continuar con las lecciones de la escuela
que solía compartir con Harriet y Charlotte.

Pero aunque ya no era alumna de la señorita Robson,
había una escuela en la cual esta querida niña estaba
aprendiendo unas lecciones muy preciadas;
y era la escuela de Cristo.
Allí aprendía diariamente lo que solo puede aprenderse del Divino Maestro.
Aprendía a soportar el dolor, el cansancio, y la soledad con paciencia.
Aprendía a deleitarse en las Sagradas Escrituras, que amaba leer.
Y sobre todo, aprendía a esperar, y a orar a ese bendito Salvador,
por el que sentía confianza para acercarse como su Padre y su Amigo.
Supondrán que ahora podía beneficiarse del poema con el que concluimos el capítulo anterior.
Verdaderamente,
ella a menudo buscaba cualquier cosa que tendiera a fortalecer su paciencia,
y por lo tanto se deleitaba en recitar el poema con frecuencia.

Ella no fue la única que se benefició de su aflicción; pues sus jóvenes amigas,
al ver la calma y la tranquila perseverancia con que sobrellevaba
las muchas dificultades que padecía debido a su condición,
estaban muy dispuestas a seguir su buen ejemplo.
Y a menudo, cuando ellas se encontraban al punto de ser "`vencidas por el mal,`"^
footnote:[Romanos 12:21]
su institutriz las animaba a acompañarla al sillón de Gertrudis,
donde se veían forzadas a ver una viva expresión
de la belleza de un "`espíritu tierno y sereno,`"^
footnote:[1 Pedro 3:4]
y a contrastarlo con la fealdad de sus propios temperamentos
que a veces eran desenfrenados e impulsivos.
De hecho, como dijo el señor Allen, "`ella se mostró como una pequeña y querida maestra,
cuyo silencio mismo predicaba un sermón aleccionador.`"

Todos necesitamos estas lecciones que la aflicción,
y solamente la aflicción puede enseñarnos.
Más aún, las necesitamos a una temprana edad,
cuando los temperamentos son elevados y desenfrenados,
y cuando el dolor y el sufrimiento no suelen experimentarse con frecuencia.
Debido a que casi no conocen el sufrimiento,
los niños y las personas jóvenes son a veces propensos
a ceder a algún sentimiento egoísta de insatisfacción,
cuando la enfermedad o los padres los limitan.
Este fue el caso de Harriet Allen un día, con respecto a Gertrudis; quien,
después de haber estado mucho mejor la noche anterior,
(dando esperanzas de que en poco tiempo podría bajar al salón),
al día siguiente se encontraba tan mal que,
en lugar de suscitar cualquier expectativa de este tipo,
había más bien un motivo mayor para temer que no saliera nunca más de su habitación.

Ahora, Harriet era una niña sensible, y, como ya les había contado,
había mejorado mucho bajo la sabia instrucción de la señorita Robson.
Tampoco carecía de sentimientos tiernos, sino que, en general,
se comportaba muy amable con la pobre niñita en su estado de debilidad.
Sin embargo, sus emociones eran fuertes, y le desagradaba tanto todo lo que era aburrido,
(como sin duda alguna,
se considera la habitación de un enfermo por los que no comprenden en absoluto su valor),
que en ocasiones era una gran prueba para ella mostrar la ternura y la
consideración hacia Gertrudis que sus difíciles circunstancias requerían.

Llena de esperanza por la mejoría del estado de salud
de su joven amiga desde hacía varios días,
y especialmente la noche anterior,
la mañana siguiente corrió a su dormitorio tan pronto como se vistió,
no tanto como para saber cómo se sentía Gertrudis,
sino para contarle acerca de todas las cosas que ella había
planeado para entretenerla cuando se dirigiera hacia abajo.
Totalmente desprevenida para la desilusión, no solo se sorprendió, sino que se enfadó,
al ver que su apresurada entrada a la habitación
era frenada por el dedo levantado de Sara,
que exclamó suavemente: "`¡shh, shh!`"

"`Oh, señorita Harriet, ¡la has despertado! dijo Sara, con gran aflicción,
mientras que Gertrudis, gimiendo del dolor, abrió sus ojos,
evidentemente sobresaltada después de que Harriet abrió la puerta.

"`¡Ay de mí! Esperaba encontrarte en el sillón de la guardería, y no en la cama,`" dijo,
dirigiéndose a Gertrudis; "`¿pensé que anoche estabas casi recuperada?`"

"`Ella está lejos de eso,`" dijo Sara, "`¡pobrecita!`"
Y me gustaría, señorita Harriet, que no entraras a la habitación de esa manera;
despertándola de su única hora de sueño que ha tenido desde las dos de la mañana.`"

Está escrito que "`la palabra hiriente hace subir la ira;`"^
footnote:[Proverbios 15:1 NBLA]
y estas palabras se sintieron extremadamente hirientes para Harriet.

"`¡Me gustaría que consideraras con quién estás hablando!`" dijo muy enojada;
y desahogando algunos de los muchos sentimientos
desagradables que pesaban sobre su espíritu,
continuó:
"`¡Estoy segura que mamá nunca aprobaría que me reprendieras de esta manera tan impertinente!`"

"`Bien, no pienso discutir contigo,`" dijo Sara;
"`si tuvieras algún sentimiento apropiado en este momento,
creo que no estarías discutiendo, e inquietando a la pobre niña que está sufriendo.`"

Casi nada enfurece a las personas egoístas tanto como que se les acuse de falta de sentimientos;
así que Harriet continuó murmurando sobre cómo Sara
procedió hasta que la pobre pequeña inválida,
muy débil para interponerse, y muy exhausta por el dolor como para soportar el ruido,
estalló en un río de lágrimas.

Esto puso fin a la paciencia de Sara; que, a decir verdad,
había sido puesta profundamente a prueba por el comportamiento insensible de Harriet,
tanto hacia ella como también hacia la pequeña paciente.
Así que, sin más preámbulos, tomándola del hombro,
la sacó silenciosamente de la habitación; diciéndole al mismo tiempo,
"`No se te permite hablar, señorita Harriet.
Ya sea que te sientas ofendida o no, no te quedarás aquí causando tanto ruido.`"

¡Qué ofensa más grande contra el honor de una niña de catorce años! ¿Qué debía hacer?
¿Pasarla por alto?
No, ella no podía hacer eso.
¡Nunca lo haría! Tales eran los pensamientos que llenaban
la mente de Harriet mientras entraba al comedor,
que, al estar más temprano de la hora habitual de reunión,
esperaba encontrarlo vacío. Pero se equivocó;
su padre estaba sentado en su acostumbrado lugar, con la Biblia abierta delante de él,
leyéndola.

Era de costumbre que los niños, al ver por primera vez a sus padres por la mañana,
y al despedirse de ellos por la noche, se acercaran a besarlos.
Pero el corazón de Harriet, en ese momento,
no estaba dispuesto a brindar ninguna muestra de cariño. ¡Tal es
la triste consecuencia de alimentar los malos sentimientos!
Como lo señaló un gran poeta, en cierta ocasión, "`No vienen como espías solitarios,
sino en batallones.`"

El señor Allen volvió su cabeza hacia la puerta que se abría, y, viendo a Harriet,
extendió su mano, aunque su mirada continuaba viendo el libro, mientras decía:
"`Buenos días, mi querida.`"

Harriet se acercó y besó su mejilla, como de costumbre,
cuando le dio su saludo habitual del día;
pero apenas habló lo suficientemente alto como para ser escuchada.

"`Me temo que la pobre Gertrudis no está muy bien
de nuevo,`" dijo todavía pasando las páginas,
como si estuviera buscando un versículo o un capítulo en particular.
Fue una suerte para Harriet que la atención de su
padre estuviera concentrada en otra cosa,
y que no viera la inquietante expresión de su rostro cuando contestó:
"`Creo que por mucho tiempo ya, no permanece bien, papá.`"

"`¡Pobre niñita!`" respondió, "`ella ha sido profundamente probada;
pero es una niña dulce y paciente.
Una pequeña y querida santa;`" él continuó, con su mirada puesta sobre el libro,
y hablando como si estuviera afirmando algo para sí mismo,
en lugar de dirigirse a otra persona.
Al abrirse de nuevo la puerta, Charlotte entró en la habitación,
lo que le hizo volver de nuevo su cabeza.
Después de haber dado y recibido el saludo habitual, al igual que Harriet,
Charlotte se acercó a la ventana en donde Harriet estaba apoyada,
aparentemente ocupada contemplando el jardín. Charlotte,
ignorante de la tormenta que se estaba produciendo en el pecho de su pobre hermana,
se abalanzó hacia ella, y quizás de una forma un poco más brusca de lo normal,
puso su mano sobre el hombro de Harriet para apoyarse
y sentarse en el asiento de la ventana.

"`¡Cómo puedes ser tan imprudente Charlotte!,`" exclamó Harriet; "`¡te aseguro,
que has roto mi vestido con tu furia!`"

¡Pobre Harriet!
En ese momento no estaba consciente de dónde se encontraba la furia más peligrosa;
y que algo mucho más preciado que su vestido era entonces su víctima.

"`¿Romper tu vestido?`"
respondió Charlotte,
cuyo temperamento no era en lo absoluto más apacible que el de su hermana,
y que se resintió de ese rudo,
y--por lo que se deduce de la ausencia de algún daño
visible en el vestido--injusto ataque contra ella.
"`Estoy segura de que no dañé tu vestido!`"

Aunque el tono de estas enfurecidas palabras era un tanto moderado,
aun así alcanzó los oídos de su padre, que les preguntó acerca del asunto.
Al inicio, ninguna de las dos respondió; pero cuándo él procedió a decir,
que era muy triste escuchar esa discusión entre ambas,
y que se había alegrado en pensar que ellas habían, en gran medida,
logrado dominar el mal en sus corazones que ocasionaba tales rencillas,
Harriet comenzó justificándose al decir: "`¡Charlotte fue la imprudente!
Yo solo estaba mirando tranquilamente por la ventana, y ella se abalanzó de golpe,
lo suficiente como para tirarme.`"

"`Oh, Harriet, estoy segura que no lo hice!
Papá, te mostraré...`"

"`No quiero que me enseñes más de lo que ya estoy viendo,`" respondió el señor Allen.
"`Puedo ver, por el semblante de Harriet, que no está de buen humor,
y entonces es probable que descargue sus sentimientos desagradables
sobre la primera cosa o persona que se atraviese en su camino.
Ven aquí, Harriet,
ven a mí;`" y extendió su mano hacia ella una vez más. Y con un corazón
que estaba empezando a ablandarse (aunque todavía no estaba blando),
se dirigió hacia él.

"`¿Qué es lo que te molesta, mi niña?`" dijo este buen padre,
poniendo su brazo tiernamente alrededor de ella.
"`Dime qué te hace infeliz, porque veo que estás infeliz.`"

Sin decir una palabra,
Harriet recostó su cabeza sobre el hombro de su padre y lloró amargamente.
Y Charlotte, aunque apenas sabía por qué, sintió que debía llorar también.

Finalmente,
Harriet respondió a los consuelos y a las tiernas preguntas de su cariñoso padre,
diciéndole que era un mal sentimiento de enojo debido a la recaída de Gertrudis,
lo que la había impulsado a ser egoísta y descortés en su forma de actuar esa mañana.
Ella no se refirió al altercado que había ocurrido entre ella y Sara, sino que dijo,
y con sinceridad,
que la intranquilidad de su consciencia al saber que le había ocasionado dolor y molestia
a Gertrudis en un momento cuando las aflicciones de su cuerpo eran muy duras,
la inquietaban e irritaban tanto,
que estaba en condiciones de pelearse con Charlotte por sólo tocarla.

"`Pero lo siento mucho, querida Charlotte,`" añadió. No necesitó agregar algo más,
pues su hermana corrió hacia donde ella, y,
mientras sus dos queridas niñas se abrazaban y se perdonaban, su padre,
con ojos llorosos, rodeó a ambas con sus brazos y las apretó contra su corazón.

"`¡Este es el bálsamo para cada herida, mis niñas!`" exclamó. "`¡Este precioso amor!`"
Se mantuvo en silencio por unos momentos, con la cabeza apoyada sobre su mano.
Después, volvió a hablar: "`Es una prueba para ti,`" dijo,
"`es una prueba para todos nosotros, que una enfermedad tan prolongada,
tocara la puerta de nuestra casa.
Pero, ¿quién nos la manda?`"
y las miró seriamente a ambas, mientras repetía, "`¿quién la manda?`"

"`El Señor la manda,`" dijo Harriet pensativamente, "`y debemos soportarla.`"

"`Debemos hacer más que tan solo soportarla, mi amor,`" respondió el señor Allen;
"`debemos aprovecharla como un medio bendito de crecimiento espiritual.
Aunque soy viejo, la aflicción de la pobre Gertrudis me ha beneficiado a mí también,
y me ha enseñado mucho;`" y sonrió.

"`Oh papá,`" dijo Charlotte, "`¡cuánto debemos aprender nosotras entonces!`"

"`Bien, espero y creo que ambas están aprendiendo bastante.
Están aprendiendo a ser gentiles;--sí, sí, he visto ejemplos de ello,
y los he visto con satisfacción y agradecimiento.
Es en estos momentos de prueba cuando se manifiesta el bien o el mal de cada corazón.
Y si en ocasiones una fea y mala hierba es encontrada entre algunas lindas flores,
¿qué debemos hacer sino arrancarla?
¿No es así, mi Harriet?`"

Harriet sonrió asintiendo,
y cuando la señora Allen y la señorita Robson entraron luego a la habitación,
se convocó al resto de la familia, y el señor Allen escogió la lectura de la mañana,
la parábola del Buen Samaritano.
Cuando llegó a las palabras, "`¿y quién es mi prójimo?`"
hizo una pequeña pausa, y luego repitió, "`¿quién es mi prójimo?
Observen,`" continuó diciendo,
"`observen la manera en que respondió nuestro Señor a esta pregunta.
No lo hizo con una descripción extensa,
que el temperamento inquisitivo del hombre al que Él se dirigía,
habría reprochado y discutido, y probablemente menospreciado.
En vez de eso, le ofreció un espejo en el que podía contemplar su propia conciencia,
y ver cuál era la conducta que un prójimo debía mostrar hacia otro,
y en el que también podía detectar hasta qué punto
él mismo lo había alcanzado o se quedaba corto.`"

El señor Allen procedió entonces a leer la parábola,
sin hacer algún otro comentario hasta que finalizó. Luego,
llamó la atención de sus oyentes con algunos pensamientos,
que dijo que siempre venían a su mente cada vez que leía esta porción de la Escritura.

"`No voy a decir,`" señaló,
"`que era la intención de nuestro Señor en esta parábola
representar nuestra miserable condición como pecadores,
asaltados y heridos por la malicia de satanás y de los espíritus malignos,
en cuyo poder hemos caído. No puedo decir,`" continuó,
"`que era Su intención ilustrar esto por medio del hombre que bajó de Jerusalén a Jericó,
y cayó en manos de ladrones; pero estoy seguro de esto,
que es un cuadro muy adecuado e impactante de nuestro estado real.
Estamos rodeados de ladrones, los peores ladrones, en nuestras propias pasiones malignas.
Si no fuera por estos traidores dentro de nuestra propia casa,
el adversario no encontraría una entrada tan fácil en nosotros como lo hace.`"

"`Y luego, cuando ya nos han golpeado y herido,
y nos han dejado medio muertos--¿qué ocurre después? ¿Aparece el ayudante indicado?
¡Ay, no!
El sacerdote y el Levita, ese individuo y el otro, nos miran;
pero ninguno de ellos tiene una ayuda que dar,
o consideran que no es asunto suyo molestarse con nosotros,
o temen que puedan verse involucrados en algunas dificultades si lo hacen;
o por alguna causa o la otra,
nos dejan luchar con nuestra propia miseria tan bien como podamos, y se apartan de ella,
al pasar por el otro lado del camino.
Ah, ¡ésta conducta es una clara manifestación de la naturaleza humana!
Es muy cierto lo que se nos dice,
que '`Jesús conocía lo que había en el interior del hombre.`'^
footnote:[Juan 2:25 NBLA]`"

"`Esta egoísta, distante,
y decidida forma de pasarse al otro lado de la angustia del prójimo,
dejándoles que luchen por sí mismos,
es una característica muy común en el carácter de muchas personas.
De hecho, diría que casi nadie que no tenga, en su forma de actuar,
la disposición de hacer todas las cosas como para el Señor y no para los hombres,
es probable que posea esta característica.
El egoísmo está en la raíz y en la rama; por más que se pode,
no se eliminará. El hacha debe ser puesta a la raíz del árbol;
la espada del Espíritu debe cortarlo.`"

"`'`Pero cierto samaritano, que iba de viaje, llegó a donde él estaba.`'`"

"`Ahora, esto es sorprendente,
porque los samaritanos eran muy despreciados por los judíos,
tanto así que no tenían ninguna interacción con ellos.
Un ejemplo de ello es el asombro expresado por la mujer
samaritana cuando el Señor le habló. '`¿Cómo es,`' dijo,
'`que Tú, siendo judío, me pides de beber a mí, que soy samaritana?
Porque los judíos no tienen tratos con los samaritanos.`'^
footnote:[Juan 4:9 NBLA]`"

"`¿Por qué, entonces, este individuo,
que era de una gente aborrecida por aquellos a los que Jesús se dirigía,
iba a ser elegido por Él como un representante de un comportamiento amable y edificante,
por encima del sacerdote y del levita, a los que, como ministros de su religión,
estaban acostumbrados a venerar y admirar?
Por esta razón, considero, que el samaritano fue escogido:
para mostrarnos que '`Dios no hace acepción de personas,
sino que en toda nación el que le teme y hace lo justo, le es acepto.`'^
footnote:[Hechos 10:34-35 NBLA]`"

"`Evitemos, por tanto, mis queridos niños y personas,
toda esa limitada exclusividad que se enfoca completamente en el yo--como hizo el sacerdote
y el levita--y que pasa al otro lado de todo lo que puede producir alguna dificultad;
y sellemos en nuestros corazones y en nuestras memorias
la dulce y sincera conducta del Buen Samaritano.
'`Al día siguiente, sacando dos denarios se los dio al mesonero, y dijo: "`Cuídelo,
y todo lo demás que gaste, cuando yo regrese se lo pagaré.`"`' ¡Qué sencillo,
qué discreto! ¡He aquí, un hombre que hacía su trabajo como para el Señor,
y no para el hombre! ¡Qué enseñanza, no solo por el acto de gentileza,
sino en cuanto a la forma correcta de realizarlo! ¡Cuántas son las oportunidades en
la vida en las que se necesita tal conducta! ¡Qué hermosos son los que la practican!
Ah, éstos están entre los escondidos del Señor--los que son poco conocidos y menos
queridos--porque no se encuentran en los lugares importantes de la tierra.
El aposento del enfermo, el hogar del que sufre,
el valle de las lágrimas--éstas son sus moradas.
Allí vierten el aceite y el vino; allí vendan las heridas;
allí siguen la obra del Maestro en el Espíritu del Maestro,
dispuestos a sufrir y a compartir las cargas de los que sufren.
Porque el sufrimiento era la porción de Jesús,
y será la porción de todos Sus seguidores.`"

"`¡Oh,
precioso sufrimiento! ¡Cómo hace por nosotros lo
que ninguna otra cosa puede hacer! ¡Cómo derrite,
cómo suaviza el corazón! ¡Cómo fertiliza cada planta verde
y en crecimiento que el Padre Celestial ha plantado!
Por lo tanto, mi querida familia, pasen lo que pasen,
nunca dejen pasar la oportunidad de compartir las aflicciones de sus prójimos.
Existe una naturaleza, sin duda alguna, en todos nosotros, que se resiste al dolor,
y siempre, si pudiera,
se encontraría en el disfrute de todo lo que este mundo
ofrece para dar alegría. Pero esta es una naturaleza egoísta,
baja,
y corrupta que no tiene nada de la dignidad que pertenece a la
renuncia de nuestra propia voluntad y nuestro propio placer.
Ha sido bien descrita por una cristiana^
footnote:[Madame Guyón,
Ver su Himno titulado "`The Joy of the Cross,`" traducido al inglés por Cowper.]
de espíritu amable a través de éstas líneas:

El amor propio no ve virtud en el pesar

Considera su propio bienestar

Es toda la dicha que conoce;

Pero objetivos más nobles el amor verdadero dispone;

En la abnegación está su gozo,

En el sufrimiento su reposo.

El señor Allen cerró entonces el volumen sagrado y concluyó
la reunión de la mañana con una devota y ferviente súplica,
pidiendo que el Espíritu Santo de Aquel cuya naturaleza y cuyo nombre es Amor,
abriera en todos sus corazones la preciosa naturaleza
y el carácter del Redentor del mundo.

