== Capítulo VIII. Visitantes.

Desde el momento de la recaída de Gertrudis, mencionado en el capítulo anterior,
se fue debilitando gradualmente,
tanto que el doctor que la atendió no fue capaz de brindar un diagnóstico
esperanzador de la recuperación de esta larga enfermedad,
aunque creía que era posible que pudiera mantenerse por algún tiempo;
pues la naturaleza de su trastorno solía ser lenta en manifestar sus resultados.

Con el fin de aliviar su aflicción al cambiar el
escenario y la circunstancia tanto como fuera posible,
había sido trasladada a un dormitorio en la planta baja,
del que la llevaban diariamente al salón familiar por un período más o menos largo,
dependiendo de su capacidad para soportarlo.
Allí se reclinó en un sofá, pacífica y felizmente,
y aunque apenas era capaz de conversar,
se sentía satisfecha de encontrarse entre los que amaba tanto,
y que le profesaban el mismo amor.
Todos los miembros de la familia se esforzaban incansablemente
por hacer todo lo posible por su comodidad y bienestar,
especialmente la señora Allen, quien era una mujer con un corazón suave,
y como ya les había mencionado, bastante propensa a consentir en exceso a los jóvenes.

Su gran preocupación por alegrar y por entretener a Gertrudis la llevaba ocasionalmente
a manifestarla de una forma que la pobre niña hubiera preferido evitar;
porque, al ser tímida por naturaleza y vergonzosa en todo momento,
ahora (más que nunca) se retraía de la presencia de los extraños. Pero la amable señora
Allen (pues no tenía otra intención más que de ser amable) no se daba cuenta de esto;
y por lo tanto, en ocasiones,
cuando intentaba complacerla al invitar a su habitación a una y otra persona, ella era,
de hecho, la causante de hacerla sentir muy incómoda.

Una noche, cuando el señor Allen, la señorita Robson,
y el resto de la familia estaban fuera de la casa,
una dama llamada señora Thomson y su hija pasaron a la casa.
Eran personas que Gertrudis conocía; y al expresar su deseo de verla,
la señora Allen las llevó a su habitación;
ya que al estar más enferma de lo usual ese día, no había sido llevada a la sala.

Ahora, el caso es que,
si había personas con las que Gertrudis particularmente deseaba evitar conversar,
esas eran la señora Thomson y su hija.
¿Supongo que les gustaría saber la razón? Debo susurrarte al oído, entonces,
queridos amigos jóvenes,
que la señora Thomson era una persona que amaba mucho al mundo y las cosas del mundo,
a pesar de que hablaba bastante sobre las cosas de Dios.
Ciertamente, hablaba tanto y tan bien de los temas religiosos,
que muchas personas (incluso la señora Allen entre muchas
otras) consideraban su discurso muy edificante e instructivo.
Lo mismo sucedía con su hija Laura, que tenía alrededor de quince años,
y había aprendido a copiar las frases de su mamá,
al igual que muchas otras costumbres vacías,
y como consecuencia era tan vana y superficial como la mayoría de los jóvenes que imitan,
no lo que es bueno,
sino lo que sus mentes vanas consideran como bonito y atractivo de sus superiores.
Este tipo de imitación, por ridícula que fuera,
no era sin embargo tan ofensiva como los intentos de Laura
por adoptar el modo del discurso religioso de su mamá;
y una secreta aversión a esto,
hizo que Gertrudis se recogiera cuando las señoras se retiraron del lugar,
y Laura ocupó la silla que estaba al lado de su cama,
expresando que deseaba tener una conversación provechosa con ella.

"`Confío, mi querida,`" empezó diciendo,
"`confío en que encuentres tu mente en un estado de felicidad.`"

"`¡Claro!`" respondió Gertrudis.

"`No dudo que te son muy valiosas las promesas que experimentas del Evangelio, ¿verdad?`"

Gertrudis permaneció completamente en silencio ante esta pregunta indirecta,
y después de unos pocos momentos,
Laura la repitió en un tono tal que parecía que demandaba una respuesta.

Pero Gertrudis seguía callada; y la joven dama,
interpretando el silencio de Gertrudis como ignorancia y oscuridad de mente,
procedió a dar las lecciones que le parecieron adecuadas,
concluyendo sus puntos de vista y consejos con algunas
observaciones sobre la vanidad del mundo,
y la ventaja de "`ir a una casa de luto,
antes que ir a una casa de banquete;`"--los cuales hubieran sido muy acertados
y muy apropiados incluso en la boca de una niña de quince,
si hubiera provenido de su corazón. Pero, en este caso, esto era (a lo sumo) muy dudoso;
y Gertrudis, al no ser capaz de recibirlos ni tampoco responderlos,
comenzó a desear tan fervientemente la ausencia de su compañía, que Laura,
percibiéndola un tanto inquieta, pronto se levantó para despedirse de ella.

Apenas se había ido, cuando la señorita Robson,
habiendo regresado de caminar con Harriet y Charlotte, entró a la habitación,
dejando a las dos niñas con su madre para entretener a la señora y a Laura Thomson.

Aunque la presencia de la señorita Robson siempre era bien recibida por Gertrudis,
ahora lo era doblemente más,
tras la agotadora conversación a la que se había
visto obligada a someterse con Laura Thomson.

"`Te ves exhausta, mi Gertrudis,`" dijo la señorita Robson en tanto se aproximaba a ella.
"`Veo que has tenido algunas visitas.`"

Gertrudis le contó lo que había sucedido, y cuando concluyó,
dijo que tenía algo en su mente que deseaba decirle a la señora Allen,
solamente que tenía miedo que, habiendo sido tan amable con ella,
pareciera una muestra de ingratitud.

La señorita Robson le aseguró que sus sentimientos no serían malinterpretados,
y la animó a expresar lo que pesaba sobre su mente en relación con la señora Allen.

"`Creo, entonces,`" dijo Gertrudis, con algo de inseguridad,
"`que me alegraría mucho si ella no invitara a ningún visitante a mi habitación.`"

"`Ella lo hace por amabilidad, mi querida,`" dijo la señorita Robson,
"`y con la esperanza de entretenerte con un pequeño cambio de compañía.`"

"`Ella es muy amable,`" dijo Gertrudis; "`pero ellos no me entretienen.
Prefiero estar sola.`"

"`Es muy agradable estar sola,
cuando experimentamos buenos pensamientos;`" respondió la señorita Robson; "`y los tuyos,
mi amor, espero que sean así.`"

"`Trato de tener buenos pensamientos, señorita Robson,`" y miró seriamente a su amiga,
"`pero no siempre tengo buenos pensamientos.
Algunas veces son muy malos.
De hecho, fueron muy malos esta noche,`" y comenzó a llorar.

La señorita Robson la consoló tiernamente;
y después de un momento le preguntó acerca de la
naturaleza de los pensamientos que la afligían.

"`No creo que pueda decírtelos, eran tan terribles.`"

"`No quiero que me los digas, mi amor,`" respondió la señorita Robson,
"`si ese es el caso.
Solo quiero decirte, que te esfuerces a no temerles.
Los pensamientos malos son arrojados en nuestras mentes por el adversario de las almas,
y en ese sentido no son nuestros,
y no somos más responsables por ellos de lo que tú
tendrías que responderle a la señora Allen,
si yo tomara un frasco de tinta, y lo tirara sobre tu limpia y blanca colcha.
Los pensamientos malos que satanás echa en nuestras mentes
solamente se hacen nuestros cuando nos unimos a ellos,
y nos deleitamos en su compañía, y hablamos con ellos, y les damos cabida.
Por ejemplo,--continuando con la comparación de la tinta--no se esperaría que yo hiciera
tal cosa como arrojar la tinta sobre la colcha de la señora Allen para arruinarla,
a menos que sintiera algo de rencor hacia ella,
y escogiera satisfacer mis deseos de esa forma.
Bien, entonces, supón que no solamente hago esto,
sino que además te digo mientras lo hago: '`Oh, Gertrudis,
la señora Allen es una persona muy malhumorada, y detestable,
y tenemos el derecho de castigarla,
y de hacer lo que queramos para molestarla y disgustarla.
Ahora, ayúdame a cortar su cama de plumas y sus almohadas,
y juntas hagamos todo el daño que podamos;`'--y tú
aceptas de inmediato y empiezas a colaborar,
y a hablar conmigo sobre la mejor forma de llevar a cabo nuestros malévolos designios.
Entonces, verdaderamente, mi maldad se convierte también en la tuya; porque,
en lugar de despreciar y rechazar mis propuestas, las apruebas y te unes con ellas.
Pero, si en lugar de esto, no les haces caso;
y creyendo que no es seguro argumentar o responderles,
te esfuerzas por mantener tu mente tan quieta como puedas,
y silenciosamente exhalas una oración a tu Padre Celestial
para que te preserve del consejo de tan detestable consejero;
entonces, mi querida niña,
¿puedes creer que te unirías en mi culpa y serías considerada como partícipe de ella?`"

"`Pero supón que sí escuché al malvado,
cuando me dijo que odiara a cualquiera,`" dijo Gertrudis,
medio temblando mientras hablaba.

"`Sería muy lamentable que prestaras tus oídos ante
tales sugerencias,`" respondió su amiga.
"`Pero, Gertrudis, me equivoco bastante en relación a mi opinión acerca de ti,
si puedes albergar algunos pensamientos de amargura y odio hacia tus semejantes.
Recuerda, mi querida niña,
hay una gran diferencia entre esas emociones repentinas de descontento con los demás,
que, como acabo de decirte, pueden ser la obra de satanás,
y que también pueden surgir de los brotes de nuestra propia corrupción; yo digo,
hay una gran diferencia entre éstos y los malos pensamientos que albergamos
y que constituyen el terrible sentimiento llamado '`odio.`' Además,
mi amor, ¿a quién odias?
Amas a todas las personas que viven en esta casa, ¿no es así?

"`Oh sí, y mucho,`" y una dulce sonrisa llenó su rostro.
"`No fue con nadie de aquí que sentí esos malos pensamientos.`"

La señorita Robson consideró que podría acceder en el secreto del
malestar de Gertrudis cuando recordó su comportamiento en relación
con lo que había pasado durante la visita de Laura,
y su deseo expresado con tanta insistencia,
que la señora Allen no volviera a traerle visitantes a su habitación. Y entonces,
creyendo que le sería de gran alivio desahogar su mente,
le dijo que podría adivinar quién era la persona
que el adversario trataba de hacerla aborrecer;
y luego, agachando su cabeza al mismo nivel de Gertrudis,
susurró en su oído el nombre de Laura Thomson.

"`Oh, ¡señorita Robson! ¡Qué bien sabes leer mi corazón!`" respondió;
"`tristemente sentí esos pensamientos malos con Laura Thomson.`"

"`Supongo que te molestó que te hablara como lo hace su madre.`"

"`No estoy segura de qué me molestó más,`" dijo Gertrudis.
"`Creo que el peor sentimiento que tuve fue el que
me hizo pensar que era duro que yo estuviera aquí,
tan débil y enferma, y ella tan bien y alegre; y, y,`"--hizo una pausa.

"`¿Y estar vestida tan elegantemente, tal vez?`"
dijo la señorita Robson,
ayudándola con la confesión. "`Me atrevo a decir que pensaste que estaba muy bien vestida.`"

"`Al principio no me fijé ni en su forma de vestir.
Estaba muy feliz antes de que entrara a la habitación.
Estaba leyendo en la Biblia donde nuestro Señor dice,
'`dejen que los niños vengan a Mí; y tomándolos en los brazos, los bendecía,
poniendo las manos sobre ellos.`' Y estaba pensando en lo
dulce que Jesús debió verse con los niños en Sus brazos,
bendiciéndolos.`"
Dejó de hablar, pero, evidentemente, no por falta de tema,
sino de palabras para expresarlo.
"`No puedo describir exactamente lo que sentía,`"
continuó finalmente--"`pero estaba muy feliz.`"

"`No lo dudo, mi querida niña,`" respondió la señorita Robson.
"`Dios es muy misericordioso con Sus niños que sufren.
Él envía una lluvia misericordiosa sobre Su heredad, y la refresca cuando está cansada.
Y me atrevo a decir, Gertrudis,
que has experimentado felices momentos sobre esa cama de sufrimiento,
que no cambiarías por toda la salud, y el placer,
y las ropas finas que Laura Thomson posee.`"

"`Sí, ¡los he experimentado!`" respondió Gertrudis.
"`Fue porque nunca antes había sentido pensamientos tan infelices,
que no sabía cómo sobrellevarlos.`"

"`No eran tus pensamientos,`" dijo la señorita Robson.
"`Si lo fueran,
no tendrías tanto dolor en su compañía como el que te han ocasionado.
La verdad del caso, mi querida, es simplemente esta: Tú eres por naturaleza,
como lo somos todos, una pobre pecadora,
y tienes una raíz del mal en donde el enemigo de
tu alma lucha para obrar y producir sus malos frutos.
Él ha estado trabajando para lograrlo esta noche, al despertar sentimientos de enojo,
envidia, y amargura hacia Laura Thomson;
confundiendo y oscureciendo tu mente a través de sus engaños,
para que tú no puedas separar el mal del bien, ni saber qué viene de ti y qué de él,
con los pensamientos que tienes.
Este es un estado muy común, incluso con mentes más experimentadas que la tuya.
Y nada se puede hacer en esos momentos, excepto quedarse completamente quieta.
Mañana por la mañana habrás olvidado todo lo que ahora te inquieta.

"`Siento como si lo hubiera olvidado ya,`" dijo Gertrudis,
"`y me alegraría mucho si Laura Thomson no se haya ido aún, para verla una vez más. Y,
señorita Robson, ¿crees que a ella le gustaría que le diera un pequeño presente?`"

"`¿Qué le darías, querida mía? Ella tiene tantas cosas finas,
que me temo que no necesitará ningún regalo que puedas tener para darle, mi Gertrudis.`"

"`Oh, no estaba pensando en darle nada fino.
Era mi pequeño cuaderno de citas.
Tengo dos o tres pequeños cuadernos con citas diarias.
Pensé que me gustaría regalarle uno.
Puede hacerle bien, ¿sabes?`"

La señorita Robson aceptó de inmediato esta propuesta,
y se apresuró para ver si la joven dama y su madre aún se encontraban en el salón.

Estaban a punto de irse,
pero aceptaron quedarse por unos minutos más con el fin de complacer del deseo de Gertrudis,
de ver una vez más a Laura.

Se entregó el presente rápidamente; porque, como ya deben saber,
la forma en que Gertrudis hacía las cosas era con el menor número de palabras posibles.
Y, en efecto, fue aceptado generosa y agradecidamente; porque Laura Thomson,
con todas sus faltas, tenía algo de amabilidad en su forma de ser,
y como siempre es mucho mejor para nosotros ver el
lado bueno que el malo de nuestros semejantes,
del mismo modo es mucho más fácil,
si solamente inclinamos nuestros corazones a la práctica
de ese "`amor que no toma en cuenta el mal recibido.`"^
footnote:[1 Corintios 13:5]

Nuestra pequeña y favorita Gertrudis (porque estoy segura
de que es una de sus favoritas) sintió esto tan profundamente,
que su afectuosa despedida con Laura Thomson--en comparación
con la fría que había ocurrido tan sólo hace media hora--fuera
como un destello de rayo de sol tras una tormenta de lluvia.
Y cuando la señorita Robson, después de la partida de Laura,
la besó y le dijo que estuviera feliz ahora, y que descansara en paz, ella respondió,
"`oh, estoy feliz.
¡Me encuentro en paz!--¡Porque ahora amo a todos!`"

