== Capítulo IX. No juzguen para que no sean juzgados.

Mientras dejamos que Gertrudis pase un tiempo de quietud y reposo,
les pediré que me acompañen al salón, donde, después de que las visitas se despidieron,
sólo quedaron la señora Allen, la señorita Robson, Harriet y Charlotte;
entre las cuales tuvo lugar la siguiente conversación,
mientras estaban ocupadas en sus tareas.

Harriet.--¡Qué niña tan superficial es esa Laura Thomson!

Charlotte.--Nunca había visto algo tan absurdo.
¡Cómo se paseaba por la habitación!

Estas palabras fueron acompañadas por una variedad de movimientos sinuosos y deslizantes,
que Charlotte exhibió imitando los movimientos de Laura Thomson.

Señora Allen.--(esforzándose por no reírse).
Charlotte, Charlotte, eso está muy mal.
No deberías hacerlo, ¿no es cierto señorita Robson?

Señorita Robson.--Creo que a Charlotte no le gustaría que la representaran de esa forma.

Charlotte.--¿Me representan a mí de esa forma?
¡Espero no hacer el ridículo como lo hace Laura Thomson!

Señorita Robson.--Tal vez no aparentes ser otras personas en su forma particular.
Es decir, quizás no te pones una fachada según su manera de actuar.

Harriet.--Pero, señorita Robson, no creo que Charlotte sea en absoluto superficial.

Señora Allen.--No, honestamente, señorita Robson,
considero que estás siendo un poco dura con Charlotte.

Fortalecida por el comentario de su mamá,
Charlotte adoptó el tono de una persona maltratada, y dijo que ella creía,
que fueran cuales fueran sus defectos, no eran los de la imitación y el orgullo.
"`Y verdaderamente, señorita Robson,`" continuó,
con una osadía que no hubiera sentido o mostrado en la ausencia de su madre,
"`creo que te quedarías muy perpleja intentando mencionar cuándo
me ha visto hacer el ridículo como lo hace Laura Thomson.`"

Señorita Robson.--No me gusta sentirme perpleja, especialmente por mis alumnas; porque,
si ha de haber algo perplejo entre nosotras,
creo que me corresponde a mí presentárselo a ellas.
Así que creo, Charlotte, que debo darte la misión de resolver lo que te quiero decir.`"

Había una firmeza en la señorita Robson,
que no le permitía desviarse de su objetivo cuando lo consideraba adecuado.
La señora Allen estaba segura, por el comportamiento de la señorita Robson,
de que había algo más detrás de su comentario a Charlotte;
y como ella misma era una persona que tenía una gran aversión a
todo lo que consideraba desagradable (como corregir a sus hijos),
optó por terminar su participación en la conversación abandonando
la habitación. Tras la ausencia de su madre,
la mayor parte de la osadía de Charlotte también se marchó.
A ella le hubiera gustado mucho ponerle fin al tema,
y por eso se esforzó por conseguirlo haciendo algún comentario
a su hermana sobre el trabajo que estaba realizando.
Sin embargo, sus esfuerzos fueron en vano; porque Harriet,
determinada a conocer cuál era el objetivo de la señorita Robson,
en lugar de responder al comentario de Charlotte sobre su trabajo, retomó el tema,
rogándole a su institutriz que le dijera en qué creía que Charlotte
se había mostrado culpable de la imitación y el orgullo.

Señorita Robson.--"`No recuerdo haber dicho que fuera
culpable de ninguna de las dos cosas.`"

Harriet.--"`No, no precisamente;
pero parecía que tú
pensabas que ella era culpable de ambas.`"

Señorita Robson.--"`Le di a Charlotte la misión de
averiguar lo que quise decir con mis comentarios.
Quizás ya haya resuelto el enigma;
y entonces podrás escuchar de ella todo lo que tengo que decir sobre el tema.`"

Mientras sucedía esto, Charlotte había estado mostrando grandes signos de inquietud,
mirando en una caja de herramientas, y en otra canasta,
como si estuviera buscando algo que necesitara,
aunque sin mencionar el nombre del artículo perdido.
Harriet la forzó a volver al punto que evidentemente deseaba evitar,
al preguntarle si sabía lo que la señorita Robson quería decir.

Charlotte.--(sonrojándose)--"`Creo que sí.`"

Harriet.--"`Oh, dime entonces, quiero escuchar lo que es.`"

Señorita Robson.--"`Les daré a ambas la oportunidad de hablar.`"

Y, mientras hablaba, se levantaba para salir de la habitación;
pero Charlotte se lo impidió al lanzar sus brazos alrededor de ella,
y escondiendo su sonrojado rostro sobre el hombro de la señorita Robson,
mientras le decía susurrando: "`Querida señorita Robson, ¡no te vayas!
Oh, has hecho que me avergüence de mí misma.`"

La señorita Robson besó su mejilla con ternura.
"`La vergüenza es generalmente un sentimiento valioso, Charlotte,
y los que pueden experimentarla real y profundamente,
nunca deben perder la esperanza de un verdadero cambio
de corazón. Te dejaré mientras le cuentas a Harriet,
lo que ella desea tanto oír;
pero como te encuentras en unas circunstancias que te obligan a ser tu propia reprensora,
debo insinuarle a Harriet que no fue muy gentil de su parte alimentar
esa impaciente curiosidad que te ha arrastrado a una situación tan dolorosa.`"

Harriet.--"`En efecto,
la culpa es mía. Pero no escucharé lo que Charlotte tiene que decir;
me castigaré de esa manera.
Estoy segura, querida señorita Robson, que tienes un propósito para cada cosa que dices,
o incluso nos insinúas, y eso es suficiente.`"

La señorita Robson estaba demasiado satisfecha con
el comportamiento de sus dos amadas pupilas,
y allí dejó terminar el asunto.

Pero, como tengo la esperanza de que algunos de mis jóvenes
lectores puedan aprender de este relato,
los complaceré en descubrir el significado detrás de los
comentarios que la señorita Robson le hizo a Charlotte.
Para ello, sin embargo,
debo retomar algunas circunstancias que tan sólo ocurrieron la semana anterior,
y que solamente Charlotte y su institutriz sabían.

Sucedió una mañana que una señora que pasó a la casa,
llevaba puesto en su sombrero (como muchas damas lo hacen) algunas flores artificiales,
adornos ostentosos a los que el señor Allen se oponía en lo particular;
pues siempre que los veía decía que le parecía algo
así como una ofensa a las hermosas flores,
que imitaran su belleza con pedazos de telas de colores.
"`Si la gente desea llevar flores,`" decía, "`que las recoja frescas y naturales.
Aunque creo que es mejor que todas las cosas mantengan su lugar correspondiente;
las flores para adornar el suelo,
y el florecimiento espiritual de los buenos corazones y mentes, para adornar a las damas.
Esas son las flores que no son artificiales, y que nunca se marchitarán.`"

Ahora, entre sus otras debilidades,
Charlotte Allen era muy vanidosa y tenía un amor por la vestimenta;
que eran defectos que encontraban poco apoyo en la casa de su padre;
pues todo allí era de lo más sencillo y simple.
Pero, a pesar de ser restringida en sus deseos por aparentar,
casi siempre que veía a alguna persona vestida a la moda, sentía el deseo de imitarla.
Esa misma mañana,
se había permitido cautivar grandemente por las flores
artificiales que estaban en el sombrero de la visitante,
y las había observado y recordado tan detalladamente que,
tan pronto como la dama se marchó,
se fue al jardín para hacer un ramo de flores tan parecido como le fuera posible.
Lo hizo a una hora del día donde solía salir con la señorita Robson
y su hermana para visitar a algunas personas pobres del pueblo;
pero esa mañana, puso una tonta excusa de que deseaba ocuparse en el jardín,
y ellas junto con la señora Allen, se marcharon.

Y aquí, me detendré para señalar que es conveniente que las personas jóvenes,
siempre reconozcan ante sí mismas la verdadera razón de todas sus acciones,
especialmente cuando son del tipo que las impulsa a desear estar solas.
Ahora, en este caso, si Charlotte hubiera reconocido ante sí misma la verdad,
y hubiera dicho: "`deseo estar sola,
porque quiero ver cómo me vería con las flores en el sombrero,`"
lo más probable es que se hubiera avergonzado tanto de sí misma,
que hubiera desistido de su intención. Pero, al encubrir su propósito diciendo,
(y supongo que creyendo realmente), que iba a ocuparse en recoger flores--olvidando,
o escogiendo no recordar,
para qué iba a recogerlas--se permitió entrar en un camino torcido,
que seguramente la llevaría hacia un error mayor del que pretendía. Pero para continuar.
Seleccionó su ramo lo más parecido posible al modelo que tenía en su memoria.
Entre los tipos, había una portulaca,
y una ramita de jazmín que sobresalían por un lado de una mejilla,
y había un guisante y un poco de reseda para hacer lo mismo en el otro.

"`¡Pero también debo tener un sombrero como el de la señorita Smith!`" pensó Charlotte.
Esto era indispensable para el adorno; sin embargo,
no había ningún sombrero en su casa que fuera de ese tipo.
"`No importa, ¡el que quiere,
puede!`" y así Charlotte creyó que podía modificar
con un toque y una vuelta a su propio sombrero,
para producir el efecto deseado.
Y así, se apresuró a ir a la habitación en la que dormían ella y su hermana,
teniendo que pasar por la de la señorita Robson, que estaba contigua.

Las flores que había reunido estaban todas enlazadas entre sí,
y puestas en orden sobre el sombrero, y todas atadas ante al espejo,
y su sombrero de paja envuelto en ellas,
cuando recordó que la señorita Smith también tenía un velo que cubría su rostro parcialmente.
¿Dónde iba a conseguir un velo?
No tenía ninguno; pero la señorita Robson tenía uno, aunque casi nunca lo usaba,
excepto cuando el clima estaba muy frío. Charlotte la había visto sacarlo de su armario,
y sabía dónde lo guardaba.
¡Pero buscar en el armario de la señorita Robson en su ausencia,
y tomar algo de allí! Esto era, verdaderamente,
un plan alarmante y dudó por algún tiempo antes de que pudiera proceder.

"`Pero no vas a robar el velo,`" le susurró al oído el astuto tentador,
"`lo vas a devolver casi inmediatamente.`"

¡Pobre Charlotte! ¡Cuán claramente hubiera podido ver en cualquier otro momento la vergüenza
de tales prácticas en las que se había visto envuelta por dar un paso en falso!
Pero ahora no podía ver nada más que su propia voluntad; y entonces, para gratificarla,
se dirigió al armario de la señorita Robson, tomó el velo, y lo ató sobre su sombrero.

Adornada tal y como lucía su visitante, que no sólo estaba a la moda en su vestimenta,
sino también en su forma de ser y en su conversación,
y era vivaz e ingeniosa en sus comentarios,
y en general era un tipo de persona que era capaz de despertar algunos
sentimientos de admiración en una niña inteligente y observadora,
Charlotte procedió a imitar la forma en que la señorita
Smith había hablado durante su visita.
Dejaré que imaginen la escena;
no estoy dispuesta a exponer todas las cosas absurdas que dijo.
Quizás algunos de mis jóvenes lectores hayan conocido a una niña en algún lugar que
haya sido tentada a complacer (como lo hizo la pobre Charlotte) algún tonto deseo de
imitar el comportamiento de alguna persona a la que haya deseado parecerse--en ese caso,
ellos pueden entender tan bien como yo podría decirles,
lo extremadamente ridícula que se veía. Solamente,
les compartiré cómo concluyó el asunto,
que ciertamente fue muy doloroso e inesperado para Charlotte, quién,
en su afán por cumplir con su propósito,
se le olvidó cerrar la puerta de la habitación de la señorita Robson.
Por lo tanto, grande fue su sorpresa, cuando, al levantarse de su asiento,
y tras hacer una pequeña reverencia,
y hablar como la señorita Smith lo había hecho al despedirse: "`Mi querida señora Allen,
debo forzarme a salir;
porque ciertamente sólo por la fuerza es que salgo de tu casa;`"--grande, digo,
fue su sorpresa, e indecible su asombro, cuando sintió una mano sobre su hombro,
al mismo tiempo que una voz le preguntaba: "`¿A dónde vas?`"

"`Oh, ¡señorita Robson!`" exclamó; pues era su institutriz,
que había regresado de su caminata, como de costumbre,
pero antes de lo que Charlotte había calculado.

"`Oh, ¡señorita Robson!`"
Repitió, mientras se sentaba, en extrema perplejidad,
cubriendo su rostro con ambas manos.

"`Más bien, creo que yo debo decir, ¡Oh Charlotte!`", respondió la señorita Robson,
permaneciendo inmóvil por unos momentos con gran asombro.
Luego, mirándola seriamente, le dijo: "`¿Por qué te hiciste este ridículo sombrero,
y por qué sacaste mi velo del armario?`"

"`No sé qué decirte,`" respondió Charlotte,
comenzando a llorar amargamente,-- "`¡Estoy tan avergonzada!`"

Las flores, y los adornos,
y la forma de imitar el discurso de despedida de la señorita Smith,
hablaron por sí solos; tampoco era algo que sorprendiera demasiado a la señorita Robson,
quién había notado varias veces con preocupación,
la inclinación de Charlotte en deleitarse con las ropas finas y
con las personas que actuaban según la moda prevaleciente,
y también una tendencia (muy común en las jóvenes)
a imitar las costumbres de los mayores.

"`No te diré mucho, mi querida Charlotte,`" dijo, después de un momento en silencio,
durante el cual Charlotte sollozaba amargamente, "`no te diré mucho,
porque estoy convencida que lo que sientes ahora
te reprende mucho mejor que lo que yo pueda hacerlo.
Pero te exhorto encarecidamente a que recuerdes lo
que sientes ahora cuando esto ya haya pasado.
Sí,
te aconsejo seriamente a que tengas presente que no sólo se trata de una
tonta imitación a la que te ha llevado esta indulgencia de la vanidad,
sino también de un abuso de confianza, una violación de la buena fe, que es mucho peor.
Cuando me voy y dejo mi armario, siento que puedo confiar en tus principios,
y también en los de tu hermana,
hasta el punto de estar persuadida de que ambas se abstendrán de
entrometerse con él. No creo que hayas abierto mi armario antes,
¿verdad?`"

"`¡No, nunca lo hice!`" dijo Charlotte.
"`Solamente sabía que tú guardabas el velo allí, porque te he visto sacarlo.
¡Y pensar que, por una tontería como ésta, haría tal cosa,
perdiendo tu buena opinión!`"...y estalló nuevamente en lágrimas.

"`No vas a perder mi buena opinión,`" dijo la señorita Robson, abrazándola tiernamente.
"`Por el contrario, espero que de ahora en adelante, la merezcas más que nunca;
porque espero que lo que sucedió te haga estar más alerta de ti misma,
que no vuelvas a ser víctima de nada tan tonto y humillante.
Ven, deshagámonos de estos adornos antes de que Harriet suba a cambiarse el vestido.`"

"`¡Pasará mucho tiempo antes de que quiera volver a usar flores!`" pensó Charlotte, que,
con una especie de desprecio por su propia insensatez,
se quitó su adornado sombrero y comenzó a retirar todos su adornos.

Habría sido bueno que también hubiera pasado un largo tiempo antes
de que volviera a sentir cualquier propensión hacia la imitación;
pero aquí, creo, debo exponer nuevamente la verdad del asunto,
y decirles que fue un encubierto sentimiento de envidia
ante la ropa de moda de Laura Thomson,
lo que le causó olvidar rápidamente la situación humillante de la semana anterior.
¡Qué pobres criaturas somos cuando nos gobierna nuestra propia naturaleza maligna!

