== Capítulo X. Espíritus Apresurados.

Durante su prologada y abatida enfermedad,
había sido de gran satisfacción para Gertrudis,
escuchar de la señorita Robson y de sus jóvenes amigas Harriet y Charlotte,
sobre cómo les iban en los asuntos relacionados con la gente pobre del pueblo.
Se deleitaba en escuchar, cuáles niños habían obtenido premios en la escuela dominical,
cuáles bebés habían nacido, y qué nombres se les había puesto,
y de qué manera se utilizaban los vestiditos y las batas y otras
prendas de vestir que se confeccionaban en la casa.

También era grande la satisfacción que Harriet y su hermana tenían
al recibir y transmitir las noticias con respecto a estos asuntos.
Pero, así como es muy común encontrar en comunidades más grandes que la de Woodside,
que las malas pasiones de la naturaleza humana se
levanten y se opongan a lo que es bueno,
de igual manera, en este retirado pueblito, no faltaba esa "`contienda de las lenguas,`"^
footnote:[Salmos 31:20 LBLA]
que evidenciaba la presencia de "`una raíz que produce fruto venenoso y ajenjo`"^
footnote:[Deuteronomio 29:18]
en algunos de los feligreses del señor Allen.

Sin embargo, como el objetivo de la señorita Robson siempre era extraer algo valioso,
incluso de esas circunstancias que parecían menos prometedoras,
no se desanimaba si durante su recorrido por las casas de las personas pobres,
se encontraban a veces con un trato al que Harriet,
en la euforia de sus fogosos e inexpertos sentimientos,
describía rápidamente como una vil ingratitud.
Un día, la indignación de Harriet se encendió particularmente (de hecho,
ya se había manifestado en otras ocasiones,
aunque en menor grado) debido al comportamiento de una mujer llamada Mary Hayes.
Esta pobre mujer, habiéndose mejorado de una fiebre reumática, y,
que durante ese tiempo había recibido ayuda económica
de una sociedad benéfica dirigida por la señora Allen,
fue informada por la señorita Robson que, a partir de la siguiente semana,
su ayuda por incapacidad cesaría.

"`Por supuesto,`" exclamó Mary, "`la señora Allen puede hacer lo que desea.
Pero de esto estoy clara y segura,
que no hay nadie en el pueblo que necesite más ayuda
que yo--¡tan débil e indefensa como estoy!`"

"`Parece que has recobrado bastante bien tus fuerzas, creo,`" dijo la señorita Robson.

"`Tu voz es ciertamente más fuerte, estoy segura,`" dijo Harriet.

"`Bueno,
¡esto es suficiente para hacer que cualquiera hable fuerte!`" respondió con enojo.
"`¡Viendo que Judy Taylor sigue recibiendo su ayuda económica cada semana!`"
Luego, agregó otras palabras que eran tan excesivamente groseras e injuriosas,
que la señorita Robson, sin responderle,
llamó a sus jovencitas y se levantó para salir de la cabaña,
limitándose en desearle un "`¡buenos días!`"

Charlotte,
aunque casi tan enfurecida como su hermana debido
a la insolencia e ingratitud de la mujer,
obedeció la orden de su institutriz, y la siguió fuera de la habitación. Pero Harriet,
ignorando el hecho de que ahora se encontraba tan
enojada como la pobre mujer (aunque por otra razón),
y por tanto igual de incapaz para hablar,
se quedó de última para aleccionar a Mary Hayes sobre lo inapropiado de su conducta.

Reprender con ira, seguro debes estar,

Cualquiera que sea la falta, no es la forma de curar.

¿Podría un sabio médico ofrecer, puedes suponer,

Al enfermo su poción hirviendo para beber?^
footnote:[Dr. John Byrom]

No les relataré lo que pasó entre ambas,
porque no sería de edificación. Pueden suponer que no fue nada beneficioso,
cuando les cuente que diez minutos después,
Harriet alcanzó a su hermana y a la señorita Robson en el otro extremo del pueblo,
mostrándose tan perturbada y enojada como la misma Mary Hayes.

"`¿Cuál es el problema?`"
dijo Charlotte;
una pregunta que Harriet contestó exponiendo numerosas
y efusivas acusaciones contra Mary Hayes,
al tiempo que se toparon con la señora Thomson y su hija, quienes,
tras haber ofrecido y respondido a los saludos de costumbre, proseguían su camino.

Llena de los agitados e irritados sentimientos que
Mary Hayes había despertado en su mente,
Harriet detuvo el rumbo de la señora Thomson, diciéndole: "`Oh, señora Thomson,
espero que nunca más haga algo por Mary Hayes.
Espero que no vaya a su cabaña.`"

Sucedió que la señora Thomson en realidad iba a visitar a Mary Hayes; porque,
al vivir muy cerca de Woodside,
ella no sólo era colaboradora de la sociedad por medio de la cual
se ayudaba a los enfermos y a los pobres de ese pueblo,
sino que también solía visitarlos; y al encontrarse en una situación económica favorable,
y con una bondadosa disposición, les donaba mucho dinero y ropa.

Desde luego se encontraba muy sorprendida por el comentario de Harriet,
y al declararle que había tenido la intención de visitar a Mary Hayes,
le rogó que le contara qué ocurrió para hacer que una visita fuera tan desaconsejable.
Se dirigía a Harriet, pero tenía sus ojos puestos sobre la señorita Robson,
ya que la consideraba más adecuada para informarle del verdadero estado del caso.

La señorita Robson sonrió,
e interrumpió la apresurada y verbosa explicación que Harriet estaba exponiendo,
diciendo: "`¡Con cuidado, con cuidado, Harriet!`"

La señora Thomson también sonrió, y dijo:
"`Quizás la señorita Robson sea tan amable de brindarnos los detalles del caso.`"

Ser tratada como una niñita, sumado a las otras humillaciones que se le habían acumulado,
era más de lo que el espíritu elevado de Harriet podía soportar.
Ella permaneció orgullosamente en silencio,
mientras la señorita Robson (para quien tales escenas de la vida humana como
las que había sido testigo con Mary Hayes no eran en absoluto nuevas) informó
con tranquilidad y sencillez a la señora Thomson que la pobre mujer,
aunque recuperada de su enfermedad, no le gustó ser quitada de la lista de beneficiarios,
y que, por tanto, ella se había expresado del tema muy inapropiadamente.
"`Pero no tengo la menor duda,`" continuó, "`de que antes de que anochezca,
se encontrará muy arrepentida de su error.
Mary Hayes es una mujer muy temperamental e impulsiva y siempre dice más
de lo que quiere decir cuando se deja llevar por episodios de mal humor.
Y como usted sabe, señora Thomson,
cuando consideramos lo que significa una ayuda económica para una pobre mujer,
deberíamos comprender el dolor y la decepción que
ella podría estar experimentando al perderla.`"

La señora Thomson, quien era extremadamente amable,
podía ver fácilmente y comprender las dificultades del caso.
Por lo tanto procedió a minimizar el error de Mary tanto como pudo,
dirigiéndose en este punto a Harriet, quien, si les soy franca,
no se encontraba en disposición de sacar ningún provecho de sus palabras en ese momento.

No me extenderé en los argumentos que usó para demostrarle a Harriet
la condición ventajosa en la que ella--como hija del señor Allen,
el Pastor de Woodside--se encontraba, en comparación a la de esa pobre reumática mujer,
Mary Hayes, que se encontraba obligada a trabajar para ganarse la vida.
Tampoco les relataré los testimonios de agradecimiento, de las personas pobres,
que ella expuso para contrastar la falta de gratitud de Mary;
porque todo lo que es necesario saber,
puede deducirse de las declaraciones de Harriet cuando se ellas se marcharon.
La señorita Robson y las niñas regresaron luego a casa,
y la señora Thomson y Laura se fueron a visitar a Mary Hayes;
la señorita Robson había insistido mucho en que lo hicieran,
con la esperanza de que eso pudiera sanar las heridas
que el intenso fervor de Harriet había servido,
sin duda, para agraviar.

"`Espero, señorita Robson, que disculpes este comentario,`" dijo Harriet,
muy orgullosamente, "`pero ciertamente creo,
que si hubieras escuchado todo lo que Mary Hayes me dijo
cuando me quedé de última para hablar con ella,
difícilmente le habría parecido adecuado justificarla tanto.`"

"`Yo no justifiqué su mal comportamiento, mi querida,`" respondió la señorita Robson;
"`pero he vivido un poco más en el mundo que tú, Harriet,
y considero que es una buena regla que, al lidiar con personas molestas,
hay que dejarles la puerta abierta para que regresen
después de que su mal humor haya pasado.
Las personas temperamentales requieren de compasión, algunas veces más que las demás;
porque por lo general se hacen tanto daño a sí mismas,
que si no encuentran quién se compadezca de ellas,
y les provean una especie de "`válvula de seguridad`" para sus espíritus,
estarían en un perpetuo peligro de explotar.`"

"`Bueno, realmente, creo,`" dijo Harriet,
aún muy molesta como para ser convencida de que estaba equivocada,
"`realmente creo que eso es llevar la compasión demasiado lejos.
Puedo comprender por qué la señora Thomson está tan llena
de amor por todos sus '`amados pobres,`' como ella los llama.
Es porque ellos la adulan;
y entonces le es muy fácil hablar de '`esa interesante Sarah esto,`' o
aquella '`dulce Susan lo otro,`' como me lo acaba de hacer a mí;
y de aconsejarme que busque su amistad.
Pero que tú, señorita Robson--`" y allí paró de hablar,
indispuesta a decir todo lo que su enojo la impulsaba a decir.

"`Oh, Harriet querida, verdaderamente estás equivocada,`" dijo Charlotte.
"`Trata de olvidar a Mary Hayes.`"

"`Estoy segura, Charlotte, que si ella te hubiera hablado como lo hizo conmigo,
hubieras estado diez veces más molesta que yo.`"

"`Eso hubiera sido un panorama aterrador,`" señaló la señorita Robson.
"`Me alegro mucho de que Charlotte se haya librado
del peligro de exponerse así ante nosotras.`"

"`¿Pero qué fue lo que te dijo?`"
preguntó Charlotte.

"`Oh, ella me dijo que no necesita ser enseñada por una niña como yo,
a quien ella vio hace poco en pañales.
Y cuando yo le dije que ella debía cultivar la mansedumbre y humildad,
'`¡Mansedumbre ciertamente!`' dijo, '`Oh sí, tú eres muy mansa! ¿No sabes que te conozco,
señorita Harriet, desde que estabas en tu cuna?`' ¿Qué piensas de eso?`"
Había algo en las condiciones de este caso--que no me atreveré
a describirlo--pero ciertamente había algo que,
cuando Harriet concluyó su relato diciendo: "`¿Qué piensas de eso?
hizo que la señorita Robson girara la cabeza para ocultar una sonrisa.

Ya habían llegado a la casa,
y Harriet aún seguía "`tocando la misma nota`" acerca de sus ofensas.
La señorita Robson, por lo tanto, hablando con bastante firmeza,
le rogó que no hablara más del tema.
"`Tanto tú como Mary Hayes serán personas muy diferentes
antes de que vayan a la cama esta noche,
no lo dudo,`" dijo.

"`Puede que sea el caso, y espero que lo sea con Mary Hayes,`" respondió Harriet;
"`pero en cuanto a mí, estoy muy segura de que mantendré mi opinión;
que he sido tratada de una manera muy injusta.
Pero allí está mamá,`" exclamó,
mientras observaba a la señora Allen acercándose para encontrarlas
al otro lado del jardín. "`Veré qué es lo que tiene que decir;`"
y sin hacer una pausa para escuchar a la señorita Robson decir,
"`quédate, quédate un momento,`" había enganchado su brazo con el de su mamá,
acercado su cabeza cerca de la suya,
y la llevó a un lado para caminar juntas en el camino de piedra,
comunicándole rápidamente a la señora Allen todo lo que había sucedido,
antes de que la señorita Robson pudiera intervenir.

Al ver que la situación era irremediable por el momento en lo que se refería a Harriet,
la señorita Robson deseaba aprovecharla con Charlotte; quien,
aunque estaba bastante insatisfecha con la manera en que su hermana fue tratada,
estaba sin embargo en una disposición de escuchar con el debido respeto,
lo que su institutriz deseaba decirle.

"`Ahora tienes una oportunidad de aprender una lección,
Charlotte,`" dijo la señorita Robson,
mientras le indicaba tomar asiento a su lado en la banca del jardín,
"`que a menudo tendrás motivo para recordar;
y es que debes dejar pasar un corto tiempo antes de que hables o actúes,
cada vez que te alteres.
Intentar hacer algo bueno en esos momentos es como
echarse a la mar en medio de una tormenta.
En este preciso momento,
nuestra querida Harriet se está apresurando a encontrar consuelo y calma
para su mente al descargar sus sentimientos reprimidos al oído de su madre.
¿Y cuál será el resultado?
Ciertamente, ella obtendrá toda la lástima que busca para sí misma.
La naturaleza mala y egoísta llegará hasta aquí para hacer su voluntad.`"

"`¿Es a una naturaleza mala y egoísta, querida señorita Robson,
a la que Harriet está cediendo?`"
preguntó Charlotte.
"`¿No le parece bien a ella que mamá deba saber qué
mujer más malagradecida y descortés es Mary Hayes?`"

"`Le haría mucho mejor a Harriet que recuerde ese bendito consejo del apóstol,
que ha escuchado a menudo, y que creo, que incluso se lo sabe de memoria: '`Hermanos,
aun si alguien es sorprendido en alguna falta, ustedes que son espirituales,
restáurenlo en un espíritu de mansedumbre, mirándote a ti mismo,
no sea que tú también seas tentado.`'^
footnote:[Gálatas 6:1]
Esto sería lo más correcto que Harriet podría hacer,
viendo que ella es excesivamente propensa a ser tentada con un espíritu temperamental.`"

"`Pero, ¿cuál sería la consecuencia de la que estabas hablando, señorita Robson?`"

"`Creo que es probable que al tomar ese camino,
le traerá mucho dolor y remordimiento a Harriet;
porque lo más probable es que la pobre mujer, Mary Hayes,
cuando se enfríe del calor del momento,
se encontrará extremadamente arrepentida por lo que dijo, y deseará no haberlo dicho.
Naturalmente temerá lo que todo esto pueda provocar.
Ella temerá que, si se lo repite a la señora Allen o a tu papá,
pueda hacer que se disgusten tanto como para retirarle todas las demás ayudas que le dan,
junto con la económica que ya ha sido descontinuada; y sintiéndose así,
no dudará en venir a la casa para disculparse con Harriet, y quizás conmigo también,
y con seguridad suplicarnos que nos abstengamos de contarles lo sucedido a tus padres.`"

"`Oh, "`¡cuánto lamentaría que ese fuera el caso!`" dijo Charlotte.

"`Ya no hay nada que hacer,`" respondió la señorita Robson, "`porque Harriet, sin duda,
ya le debió haber contado lo sucedido a tu mamá,
y haberlo dicho también bajo la influencia de sus fuertes emociones
que probablemente le dio un aspecto aún más exagerado y agravado.`"

"`Ahora lo puedo ver,`" dijo Charlotte, después de unos momentos en silencio,
"`verdaderamente, ahora puedo ver que es mucho mejor dejar pasar un poco de tiempo,
en lugar de hablar cuando estamos molestos.
Oh, cuánto se arrepentirá Harriet si Mary Hayes viene y se disculpa.
Cuánto lamentará por haber sido tan impulsiva.`"

"`Sí,
pero lamentablemente esta es la manera en que las personas impulsivas
e impacientes deben ser enseñadas,`" dijo la señorita Robson,
"`del mismo modo en que Gedeón tuvo que enseñar a los hombres de Sucot, es decir,
con '`espinos y abrojos.`'^
footnote:[Jueces 8:16]
Sin embargo, querida Charlotte, como tú, felizmente, no estás implicada en este error,
sino que te encuentras en una posición tranquila de espectadora,
esfuérzate por aprender tu lección de una manera más serena.
Puede resumirse en unas pocas y preciosas palabras--'`estén quietos,
y vean la salvación del Señor.`'^
footnote:[Éxodo 14:13; 2 Crónicas 20:17]
Cuando la conmoción de cualquier tipo te inquieta, incluso la placentera,
debes estar quieta, esto es,
esforzarte por no actuar o hablar hasta que tus emociones se hayan calmado;
porque al actuar o hablar en esos momentos,
es probable que te pongas en circunstancias que sean insensatas o pecaminosas,
que lamentarás cuando estés más tranquila.
Si nuestras emociones se agitan por un objeto de placer que tenemos delante,
la naturaleza vana se lanzará a hacer tonterías,
así como el pequeño Johnny salta y brinca y hace cosas absurdas,
porque su expectativa es divertirse.
Y, cuando la agitación de nuestras emociones es de un tipo más oscura y dolorosa,
entonces se consumirá en furia, que, a parte de ocasionar insensatez,
traerá pecado y vergüenza sobre nosotros.
Por tanto, siempre que te sientas muy satisfecha, o muy dolida, querida niña,
quédate quieta;
y pronto sentirás algo mejor que tú misma y que tus propios sentimientos desenfrenados,
que busca salvarte de esas palabras y acciones de las que, en un corto tiempo,
estarás verdaderamente agradecida de ser librada.`"

Cuando el dolor o la alegría te opriman fuertemente,

Mantente en alerta especialmente;

Entonces un menor peligro de actuar mal encontrarás,

Un estado más sereno producirá una luz más eficaz.^
footnote:[Dr. John Byrom]

El asunto resultó justo como la señorita Robson lo había predicho.
Recién se había retirado el mantel de la mesa,
cuando Harriet fue llamada a salir del comedor porque Mary Hayes deseaba hablar con ella.
El péndulo de sus emociones había vuelto a oscilar en la otra dirección, igual de lejos.
Pero, ahora era muy tarde para solicitarle que no le comentara
nada tanto al señor como a la señora Allen de su mala conducta;
porque Harriet, no había guardado nada sin decir al respecto.
Obedeciendo el apresurado y efusivo impulso que la llevó a precipitarse
y a exponer sus sentimientos tan pronto que vio a su mamá,
ella había ocasionado (como podía percibirlo ahora) un gran mal a la pobre mujer.
Porque la señora Allen había quedado tan disgustada con lo que le había contado,
que se lo hizo saber al señor Allen durante la cena;
y él por su parte se encontraba igualmente insatisfecho,
así que la pobre Mary Hayes tenía motivos suficientes para temer que su
mal comportamiento produjera algunas consecuencias serias.

Harriet,
sintiéndose realmente arrepentida por lo que había hecho para empeorar el asunto,
perdonó de inmediato la ofensa que le había hecho,
y se encargó de hablar con la señorita Robson con la esperanza
de que la pudiera ayudar a resolver el problema.

Me atrevo a decirles, mis jóvenes lectores, que podrán, con pocas palabras,
formarse una idea del doloroso estado humillante de Harriet,
cuando se dirigió donde la señorita Robson y le relató
lo arrepentida que estaba Mary Hayes,
y luego le habló de su propia angustia por la imprudencia con la
que ella tal vez había hecho infructuosa la penitencia de Mary.
En efecto, estaba verdaderamente desconsolada y arrepentida por lo que había hecho,
y prometió, con el ferviente deseo de poder cumplir su palabra,
que seguiría el consejo de su muy respetada amiga e institutriz,
que ahora le había causado una profunda impresión; a saber,
que siempre que se precipitara a manifestar sus sentimientos,
trataría de quedarse quieta, y dejar pasar un poco de tiempo,
antes de hablar o de actuar.

"`Tienes que aprender cómo sobrellevar sentirte incómoda por un tiempo,
Harriet,`" dijo la señorita Robson.
"`Es ese precipitarse por conseguir algo que te satisfaga o te consuele,
lo que ocasiona el problema.
Cuando te sientas ofendida, sopórtalo.
Pase lo que pase, sobrellévalo por un tiempo; no te apures por vengarte.
Si realmente has sido maltratada,
ten por seguro que se solucionará en el tiempo adecuado, y de la manera adecuada;
pero apresurarte en vengarte, muestra claramente que cometes un error.
'`Con su paciencia, ganarán sus almas.`'^
footnote:[Lucas 21:19]

Solamente agregaré, para concluir este capítulo, lo que les alegrará escuchar,
que la tranquila y sensata exposición del caso de parte de la señorita Robson,
y la disculpa de Harriet por haberse apresurado y por su temperamento,
tuvieron su debido efecto sobre el señor y la señora Allen;
y la pobre Mary Hayes fue perdonada por su imprudencia.

