== Capítulo XI. La Despedida.

Otro año más pasó en la familia,
y trajo consigo un mayor debilitamiento y fragilidad a nuestra pobre amiguita Gertrudis.

Hacía tiempo que era evidente que se estaba sucumbiendo
gradualmente a la enfermedad que la afligía,
y, por lo que ya les había comentado,
se habrán preparado para escuchar lo que pareciera ser una noticia triste.
Pero espero, que para cuando hayan leído la siguiente carta de parte del señor Allen,
en donde brinda una descripción de su pacífica partida de este valle de lágrimas,
estén más contentos que tristes cuando se despidan de ella.
Está dirigida a la dama que estuvo a cargo de Gertrudis al dejar la India,
y que la dejó bajo el cuidado del señor Allen.
Esta dama vino a verla varias veces a lo largo de su prolongada enfermedad,
y al dejarla en su última visita,
había solicitado escuchar noticias de ella de parte del señor Allen.
Se le dirigieron varias cartas en correspondencia con esa petición;
y finalmente llegó la siguiente, con la que terminaré esta pequeña narración.

[.asterism]
'''

Mi querida señora +++_______+++.

El sello negro en esta carta la habrá preparado para su contenido.
Nuestra pequeña y afligida Gertrudis se regocija ahora con los santos en la luz,
y si no fuera porque, sin duda, deseas conocer algunos detalles,
me gustaría no tener que volver a referirme de esta querida
niña más de que lo que tiene que ver con su presente estado.
Así que, disculpa mi brevedad.

El sábado pasado, ella se encontraba extremadamente débil y somnolienta,
y habiendo notado por varios días manifestaciones de que su partida se acercaba,
esperábamos que en ese día sus sufrimientos terminaran.
Pero, contrario a lo que creíamos, mostró signos de mejoría por la noche,
tanto que fue capaz de conversar un poco,
y parecía especialmente complacida de tenernos cerca, a mí y a nuestra amada amiga,
la señorita Robson.
Le leí un cuantos versículos, del capítulo 14 de Juan,
que siempre había sido una de sus partes favoritas.
Me detuve en las palabras:
"`en la casa de mi Padre hay muchas moradas,`" porque parecía que quería hacer un comentario;
pero solamente pronunció las palabras "`todas hermosas,`" y sonrió.

"`Sí, mi amor,`" le dije, "`¡todas!
No hay otras moradas como esas, Gertrudis!`"

"`¡Oh!, deseo...`" pero, como si temiera transmitir impaciencia al expresar sus deseos,
no dijo más.

"`Deseas irte, mi querida niña,`" dijo la señorita Robson.
"`Pero nosotros no queremos dejarte ir, mi querida,
mientras el Señor así te permita quedarte;`" y nuestra querida amiga,
aunque es una persona con un gran dominio propio, fue incapaz de contener sus lágrimas.

Gertrudis se mostró un poco afectada ante esto,
pero las emociones fueron rápidamente contenidas por la señorita Robson, quién,
con una agradable sonrisa, limpiando las lágrimas de sus mejillas,
le repitió a su pequeña amiga y amada alumna las siguientes líneas,
que Gertrudis se había deleitado en escucharlas a lo largo de su enfermedad.
Fueron escritas por una amiga de la señorita Robson
que se encontraba en circunstancias difíciles.

Cuando por un corto tiempo están,

Caen y mueren las rosas;

Los lirios del valle se marchitan,

Y así, ¡ay, debo hacerlo yo además!

Pero, ¿por qué me lamento

Y, por qué tengo que suspirar?

El invierno se irá pronto

Y los días de verano se van a asomar

La adorada rosa reaparecerá

Los lirios florecerán una vez más

La primavera, fresca y hermosa volverá,

y el rostro de la Creación se restaurará;

Y los santos de Dios renovados se levantarán

Con mejor vida que ésta;

Y con el Bien Supremo morarán

En la dicha infinita.

Sonrió dulcemente, como si estos pensamientos fueran muy valiosos para ella;
y cuando le dije: "`Por medio de Uno, que murió por todos,
podemos esperar la resurrección a la dicha infinita,`" exclamó fervientemente: "`Sí,
por medio de Jesús, ¡el bendito Salvador!`"

"`¿Sientes que no tienes otra esperanza, mi amor,
que la que encuentras en Él?`" le pregunté.

"`Oh no,`" respondió rápidamente.
"`Solamente pienso en Dios a través de Él--Él es el buen Amigo que intercede.`"

"`El Amigo de los pecadores,`" dijo la señorita Robson,
"`el Amigo más unido que un hermano.`"^
footnote:[Proverbios 18:24]

Ella le mostró su alegría y satisfacción en este bendito pensamiento,
pero se encontraba muy débil para expresarlo.
Nuestra querida Gertrudis, como ya lo sabes era, incluso con salud,
alguien que pocas veces expresaba sus sentimientos.

Tras haber invertido unos minutos en oración, me despedí de ella por la noche,
y las niñas y la señora Allen llegaron a su habitación con el mismo propósito, dejándola,
como era de costumbre, bajo el amable cuidado de la señorita Robson.

Habiéndonos despedido de ella en ese estado,
no nos esperábamos que nos llamaran al amanecer con la dolorosa noticia de que,
de repente, había empeorado tanto que parecía estar en la víspera de su partida.
Pero así fue.
Nos apresuramos a ir a su habitación, es decir, mi esposa y yo;
porque no quise que mis queridas niñas fueran llamadas para presenciar la escena.
Quería que ellas aprendieran de las virtudes vivas de nuestra dulce Gertrudis,
y no de las luchas físicas al partir.
Dichosamente,
estas luchas fueron de corta duración. Ella estaba
partiendo en el instante que entramos a la habitación,
con una sonrisa tan hermosa que cualquier otro sentimiento
que no fuera el de la alegría nos parecía inapropiado.
Todos nos alegramos, esto es, la señorita Robson, nuestra fiel niñera Sarah, y yo.
Pero mi pobre esposa, que aunque no era la madre de la agonizante niña,
sintió que su corazón de madre se conmovía dentro de ella,
y poniendo sus brazos alrededor de la querida Gertrudis,
mientras era sostenida por la señorita Robson, lloró amargamente.

El gris amanecer del día, y las solemnes circunstancias que me rodeaban,
me hicieron recordar poderosamente esas hermosas y conmovedoras
líneas del señor Cecil cuando falleció uno de sus hijos,
un bebé de un mes que murió al amanecer,
por lo que pronuncié en voz alta el primer verso:

No me detengas más aquí, en este lugar

Abrumada en el dolor, la más querida mamá

Tus bondadosas caricias me van a angustiar,

¡Déjame partir!
Que el día se aproxima.

"`¡Tu día se aproxima, dichosa niña!`" exclamé, en el momento en que besaba su mejilla,
y exhalaba unas palabras a Él que ve en lo secreto.

Un pequeño suspiro liberó su gozoso espíritu;
y ya sólo quedaba el dolor de transmitir la noticia a nuestros
queridos hijos de naturalezas jóvenes y alegres,
que estábamos seguros de que, por un tiempo, la considerarían como algo muy lamentable.

En efecto, fue un doloroso golpe, aunque uno que se esperaba desde hacía mucho tiempo;
y di rienda suelta a las emociones de la naturaleza por un corto tiempo.
Y cuando éstas se calmaron un poco,
me propuse a sacarle provecho a la situación para el beneficio de todos;
y espero que no haya sido infructuoso.

"`Así, mis queridos hijos,`" les dije, en conclusión,
"`hemos perdido a nuestra gentil Gertrudis; pero no hemos perdido eso que la hizo gentil.
Pues, Aquel cuyas palabras de despedida fueron: '`Yo estoy con ustedes todos los días,
hasta el fin del mundo`'--Él, que fue manso y humilde de corazón,
y llama a los que están cargados para que vengan a Él y
sean refrescados--Él permanece para bendecirnos,
y hacernos bien; para reunir a las ovejas con Su brazo, y llevarlas en su seno.
Oh entonces, mis niños,
cultiven esas dulces virtudes de ovejas que los harán
aptos para ser reunidos en Su redil;
de modo que, cuando sea y como sea, que llegue su llamado,
puedan experimentar una partida tan pacífica como la de nuestra dulce Gertrudis.`"

Sintiendo este mismo deseo tanto para mí, como para ti, mis amiga cristiana,
y para todos mis semejantes, me despido sinceramente,

John Allen.

Fin.